"""ARX VCP Domain Authority & Conformance Package.

Sprint 2B Domain-Authority Resolution.
"""

from analyst_dashboard.vcp.case_compiler import (
    TemporalReadEvent,
    VCPTemporalCaseCompiler,
    VCPTemporalCasePackage,
)
from analyst_dashboard.vcp.classifier import VCPClassifier
from analyst_dashboard.vcp.composite_methodology import (
    DOMAIN_RULE_PROVENANCE_CATALOG,
    PRODUCT_LABEL_AUTHORIZATIONS,
    DomainRuleProvenance,
    ProductLabelAuthorization,
    ProductUseStatus,
    SemanticSupport,
    SupportType,
    VCPCompositeMethodology,
)
from analyst_dashboard.vcp.conformance_oracle import (
    ADJUDICATORS,
    Adjudicator,
    CaseRole,
    IsolationLevel,
    OracleGrade,
    OracleTier,
    UsagePartition,
    AdjudicationStatus,
    CHALLENGE_IS_ORACLE_GRADE,
    CHALLENGE_IS_CASE_ROLE,
    CHALLENGE_CASES_AUTO_PROMOTED_TO_GOLD,
    SYNTHETIC_ADJUDICATOR_REPRESENTED_AS_REAL_HUMAN,
    GOLD_INDEPENDENT_ADJUDICATION,
    HOLDOUT_PRECOMMITMENT_CRYPTOGRAPHIC_PROOF,
    PREDECESSOR_HOLDOUT_COMMITMENT_HASH_VALUE,
    SUCCESSOR_HOLDOUT_COMMITMENT_HASH_VALUE,
    verify_adjudicator_authenticity,
    promote_case_grade,
    VCPConformanceCorpus,
    VCPCorpusCase,
    generate_clean_history,
)
from analyst_dashboard.vcp.domain_glossary import (
    GLOSSARY_TERMS,
    DomainTermDefinition,
    TermStatus,
    VCPDomainGlossary,
)
from analyst_dashboard.vcp.domain_source_registry import (
    VCP_DOMAIN_SOURCES,
    AuthorityClass,
    ContentUsageRight,
    DomainClaimRecord,
    DomainSource,
    VCPDomainSourceRegistry,
)
from analyst_dashboard.vcp.label_authorization import (
    LABEL_AUTHORIZATION_CATALOG,
    LabelAuthorizationRecord,
    VCPLabelAuthorizationMatrix,
)
from analyst_dashboard.vcp.mutation_harness import (
    MutationTestResult,
    VCPMutationHarness,
)
from analyst_dashboard.vcp.numeric_contract import (
    NUMERIC_SPECS,
    NumericSpecification,
    VCPNumericContract,
)
from analyst_dashboard.vcp.predicate_registry import (
    PREDICATE_DEFINITIONS,
    ConformanceRole,
    PredicateDefinition,
    PredicateResult,
    PredicateStatus,
    VCPDomainAssessment,
    VCPObservation,
    VCPPredicateRegistry,
)
from analyst_dashboard.vcp.temporal_contract import (
    DailyOHLCVBar,
    VCPTemporalContract,
)

__all__ = [
    "AuthorityClass",
    "ContentUsageRight",
    "DomainClaimRecord",
    "DomainSource",
    "VCP_DOMAIN_SOURCES",
    "VCPDomainSourceRegistry",
    "TermStatus",
    "DomainTermDefinition",
    "GLOSSARY_TERMS",
    "VCPDomainGlossary",
    "PredicateStatus",
    "ConformanceRole",
    "PredicateResult",
    "VCPObservation",
    "VCPDomainAssessment",
    "PredicateDefinition",
    "PREDICATE_DEFINITIONS",
    "VCPPredicateRegistry",
    "NumericSpecification",
    "NUMERIC_SPECS",
    "VCPNumericContract",
    "DailyOHLCVBar",
    "VCPTemporalContract",
    "TemporalReadEvent",
    "VCPTemporalCasePackage",
    "VCPTemporalCaseCompiler",
    "OracleTier",
    "UsagePartition",
    "AdjudicationStatus",
    "OracleGrade",
    "CaseRole",
    "CHALLENGE_IS_ORACLE_GRADE",
    "CHALLENGE_IS_CASE_ROLE",
    "CHALLENGE_CASES_AUTO_PROMOTED_TO_GOLD",
    "SYNTHETIC_ADJUDICATOR_REPRESENTED_AS_REAL_HUMAN",
    "GOLD_INDEPENDENT_ADJUDICATION",
    "HOLDOUT_PRECOMMITMENT_CRYPTOGRAPHIC_PROOF",
    "PREDECESSOR_HOLDOUT_COMMITMENT_HASH_VALUE",
    "SUCCESSOR_HOLDOUT_COMMITMENT_HASH_VALUE",
    "verify_adjudicator_authenticity",
    "promote_case_grade",
    "IsolationLevel",
    "Adjudicator",
    "ADJUDICATORS",
    "VCPCorpusCase",
    "generate_clean_history",
    "VCPConformanceCorpus",
    "VCPClassifier",
    "LabelAuthorizationRecord",
    "LABEL_AUTHORIZATION_CATALOG",
    "VCPLabelAuthorizationMatrix",
    "MutationTestResult",
    "VCPMutationHarness",
    "VCPCompositeMethodology",
    "DomainRuleProvenance",
    "ProductLabelAuthorization",
    "SupportType",
    "ProductUseStatus",
    "SemanticSupport",
    "DOMAIN_RULE_PROVENANCE_CATALOG",
    "PRODUCT_LABEL_AUTHORIZATIONS",
]
