"""
Deterministic Publication Integrity & Drift Detection Engine.

Validates candidate scanner snapshots against authorized version registries
and semantic fingerprints before publication into Radar.
"""

from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass
from analyst_dashboard.analyzers.scanner_contract import (
    ScannerVersionTuple,
    PublicationDecision,
    DriftClassification,
    compute_hash,
    compute_semantic_fingerprint,
    VCP_API_CONTRACT_VERSION,
    VCP_RULESET_VERSION,
    VCP_EVIDENCE_SCHEMA_VERSION,
    VCP_SCORE_MODEL_VERSION,
    VCP_DATA_PROVENANCE_VERSION,
    VCP_UNIVERSE_VERSION,
    VCP_FRESHNESS_POLICY_VERSION,
)


# Canonical Ruleset Specifications & Hashes
CANONICAL_VCP_RULESET_SPEC = {
    "name": "Minervini Volatility Contraction Pattern & Stage 2 Growth",
    "minimum_sessions": 50,
    "ma_indicators": ["SMA50", "EMA20"],
    "volatility_indicator": "ATR14",
    "stage_criteria": "Price above declining SMA50 corridor; Stage 2 Advancing; VCP 3-Stage Compression",
    "risk_reward_floor": 1.85,
    "confluence_conviction_floor": 70.0,
}
CANONICAL_VCP_RULESET_HASH = compute_hash(CANONICAL_VCP_RULESET_SPEC)

CANONICAL_VCP_EVIDENCE_SCHEMA_SPEC = {
    "fields": [
        "vcp_stage",
        "setup_pattern",
        "stage_phase",
        "sma_50",
        "ema_20",
        "atr_14",
        "breakout_pivot",
        "optimal_entry_min",
        "optimal_entry_max",
        "stop_loss",
        "take_profit_1",
        "take_profit_2",
        "risk_reward_ratio",
        "execution_status",
        "confluence_score",
    ]
}
CANONICAL_VCP_EVIDENCE_SCHEMA_HASH = compute_hash(CANONICAL_VCP_EVIDENCE_SCHEMA_SPEC)

CANONICAL_VCP_SCORE_MODEL_SPEC = {
    "model": "ConfluenceConvictionWeightedScoring",
    "technical_weight": 0.35,
    "fundamental_weight": 0.25,
    "macro_weight": 0.20,
    "catalyst_weight": 0.20,
    "ranking": "score_desc_symbol_asc",
}
CANONICAL_VCP_SCORE_MODEL_HASH = compute_hash(CANONICAL_VCP_SCORE_MODEL_SPEC)

CANONICAL_VCP_DATA_PROVENANCE_SPEC = {
    "primary_role": "OHLCV_DAILY_PRICE_HISTORY",
    "provider": "LOCAL_MARKET_DB_SQLITE",
    "fallback_provider": "YFINANCE",
    "candle_window": 60,
    "adjustment_state": "SPLIT_AND_DIVIDEND_ADJUSTED",
}
CANONICAL_VCP_DATA_PROVENANCE_HASH = compute_hash(CANONICAL_VCP_DATA_PROVENANCE_SPEC)

CANONICAL_VCP_UNIVERSE_SPEC = {
    "universe_id": "ARX_CANONICAL_LONG_TERM_V1",
    "definition": "Multi-Sector Dual-Horizon Quality Equities",
    "asset_count": 35,
}
CANONICAL_VCP_UNIVERSE_HASH = compute_hash(CANONICAL_VCP_UNIVERSE_SPEC)

CANONICAL_VCP_FRESHNESS_SPEC = {
    "max_age_hours": 24,
    "stale_threshold_hours": 48,
    "status_mapping": {"<=24h": "LIVE", ">24h": "STALE"},
}
CANONICAL_VCP_FRESHNESS_HASH = compute_hash(CANONICAL_VCP_FRESHNESS_SPEC)


# Version Registry: Maps authorized version strings to authorized specifications
AUTHORIZED_VERSION_REGISTRY: Dict[str, Dict[str, Dict[str, str]]] = {
    "MINERVINI_VCP": {
        "ruleset": {
            VCP_RULESET_VERSION: CANONICAL_VCP_RULESET_HASH,
        },
        "evidence_schema": {
            VCP_EVIDENCE_SCHEMA_VERSION: CANONICAL_VCP_EVIDENCE_SCHEMA_HASH,
        },
        "score_model": {
            VCP_SCORE_MODEL_VERSION: CANONICAL_VCP_SCORE_MODEL_HASH,
        },
        "data_provenance": {
            VCP_DATA_PROVENANCE_VERSION: CANONICAL_VCP_DATA_PROVENANCE_HASH,
        },
        "universe": {
            VCP_UNIVERSE_VERSION: CANONICAL_VCP_UNIVERSE_HASH,
        },
        "freshness_policy": {
            VCP_FRESHNESS_POLICY_VERSION: CANONICAL_VCP_FRESHNESS_HASH,
        },
    }
}


@dataclass
class PublicationEvaluationReport:
    """Report generated by publication integrity verification."""
    decision: PublicationDecision
    semantic_drift: DriftClassification
    semantic_fingerprint: str
    violations: List[str]
    changed_components: List[str]
    severity: str  # "INFO", "WARNING", "CRITICAL"

    @property
    def drift_classification(self) -> DriftClassification:
        return self.semantic_drift


class ScannerPublicationIntegrityEngine:
    """Evaluates candidate snapshots for deterministic publication integrity."""

    @classmethod
    def get_canonical_vcp_fingerprint(cls) -> str:
        """Returns the canonical semantic fingerprint for MINERVINI_VCP v1.0.0."""
        return compute_semantic_fingerprint(
            scanner_id="MINERVINI_VCP",
            ruleset_hash=CANONICAL_VCP_RULESET_HASH,
            evidence_schema_hash=CANONICAL_VCP_EVIDENCE_SCHEMA_HASH,
            score_model_hash=CANONICAL_VCP_SCORE_MODEL_HASH,
            data_provenance_spec_hash=CANONICAL_VCP_DATA_PROVENANCE_HASH,
            universe_definition_hash=CANONICAL_VCP_UNIVERSE_HASH,
            freshness_policy_hash=CANONICAL_VCP_FRESHNESS_HASH,
        )

    @classmethod
    def evaluate_publication_integrity(
        cls,
        scanner_id: str,
        candidate_version_tuple: ScannerVersionTuple,
        ruleset_hash: str,
        evidence_schema_hash: str,
        score_model_hash: str,
        data_provenance_spec_hash: str,
        universe_definition_hash: str,
        freshness_policy_hash: str,
    ) -> PublicationEvaluationReport:
        """Alias for evaluate_candidate_publication matching Section 14 nomenclature."""
        return cls.evaluate_candidate_publication(
            scanner_id=scanner_id,
            version_tuple=candidate_version_tuple,
            ruleset_hash=ruleset_hash,
            evidence_schema_hash=evidence_schema_hash,
            score_model_hash=score_model_hash,
            data_provenance_hash=data_provenance_spec_hash,
            universe_hash=universe_definition_hash,
            freshness_policy_hash=freshness_policy_hash,
        )

    @classmethod
    def evaluate_candidate_publication(
        cls,
        scanner_id: str,
        version_tuple: ScannerVersionTuple,
        ruleset_hash: str,
        evidence_schema_hash: str,
        score_model_hash: str,
        data_provenance_hash: str,
        universe_hash: str,
        freshness_policy_hash: str,
    ) -> PublicationEvaluationReport:
        """
        Enforce strict publication integrity gates:
        1. All component versions must be recognized in the registry.
        2. Component content hashes must match authorized hashes for the declared versions.
        3. No silent semantic drift or version regressions allowed.
        """
        violations: List[str] = []
        changed_components: List[str] = []

        registry = AUTHORIZED_VERSION_REGISTRY.get(scanner_id)
        if not registry:
            return PublicationEvaluationReport(
                decision=PublicationDecision.QUARANTINE,
                semantic_drift=DriftClassification.SILENT_SEMANTIC_DRIFT,
                semantic_fingerprint="",
                violations=[f"Unregistered scanner_id '{scanner_id}'"],
                changed_components=["scanner_id"],
                severity="CRITICAL",
            )

        # 1. Ruleset check
        expected_ruleset = registry["ruleset"].get(version_tuple.ruleset_version)
        if expected_ruleset is None:
            violations.append(f"UNKNOWN_RULESET_VERSION: '{version_tuple.ruleset_version}'")
        elif expected_ruleset != ruleset_hash:
            violations.append(
                f"HASH_CHANGED_AND_VERSION_UNCHANGED: ruleset hash mismatch on version '{version_tuple.ruleset_version}'"
            )
            changed_components.append("ruleset")

        # 2. Evidence schema check
        expected_schema = registry["evidence_schema"].get(version_tuple.evidence_schema_version)
        if expected_schema is None:
            violations.append(f"UNKNOWN_EVIDENCE_SCHEMA_VERSION: '{version_tuple.evidence_schema_version}'")
        elif expected_schema != evidence_schema_hash:
            violations.append(
                f"HASH_CHANGED_AND_VERSION_UNCHANGED: evidence schema hash mismatch on version '{version_tuple.evidence_schema_version}'"
            )
            changed_components.append("evidence_schema")

        # 3. Score model check
        expected_score = registry["score_model"].get(version_tuple.score_model_version)
        if expected_score is None:
            violations.append(f"UNKNOWN_SCORE_MODEL_VERSION: '{version_tuple.score_model_version}'")
        elif expected_score != score_model_hash:
            violations.append(
                f"HASH_CHANGED_AND_VERSION_UNCHANGED: score model hash mismatch on version '{version_tuple.score_model_version}'"
            )
            changed_components.append("score_model")

        # 4. Data provenance check
        expected_prov = registry["data_provenance"].get(version_tuple.data_provenance_version)
        if expected_prov is None:
            violations.append(f"UNKNOWN_DATA_PROVENANCE_VERSION: '{version_tuple.data_provenance_version}'")
        elif expected_prov != data_provenance_hash:
            violations.append(
                f"HASH_CHANGED_AND_VERSION_UNCHANGED: data provenance hash mismatch on version '{version_tuple.data_provenance_version}'"
            )
            changed_components.append("data_provenance")

        # 5. Universe check
        expected_univ = registry["universe"].get(version_tuple.universe_version)
        if expected_univ is None:
            violations.append(f"UNKNOWN_UNIVERSE_VERSION: '{version_tuple.universe_version}'")
        elif expected_univ != universe_hash:
            violations.append(
                f"HASH_CHANGED_AND_VERSION_UNCHANGED: universe definition hash mismatch on version '{version_tuple.universe_version}'"
            )
            changed_components.append("universe")

        # 6. Freshness policy check
        expected_fresh = registry["freshness_policy"].get(version_tuple.freshness_policy_version)
        if expected_fresh is None:
            violations.append(f"UNKNOWN_FRESHNESS_POLICY_VERSION: '{version_tuple.freshness_policy_version}'")
        elif expected_fresh != freshness_policy_hash:
            violations.append(
                f"HASH_CHANGED_AND_VERSION_UNCHANGED: freshness policy hash mismatch on version '{version_tuple.freshness_policy_version}'"
            )
            changed_components.append("freshness_policy")

        semantic_fingerprint = compute_semantic_fingerprint(
            scanner_id=scanner_id,
            ruleset_hash=ruleset_hash,
            evidence_schema_hash=evidence_schema_hash,
            score_model_hash=score_model_hash,
            data_provenance_spec_hash=data_provenance_hash,
            universe_definition_hash=universe_hash,
            freshness_policy_hash=freshness_policy_hash,
        )

        if violations:
            return PublicationEvaluationReport(
                decision=PublicationDecision.QUARANTINE,
                semantic_drift=DriftClassification.SILENT_SEMANTIC_DRIFT,
                semantic_fingerprint=semantic_fingerprint,
                violations=violations,
                changed_components=changed_components,
                severity="CRITICAL",
            )

        return PublicationEvaluationReport(
            decision=PublicationDecision.PUBLISH,
            semantic_drift=DriftClassification.NO_SEMANTIC_DRIFT,
            semantic_fingerprint=semantic_fingerprint,
            violations=[],
            changed_components=[],
            severity="INFO",
        )
