"""Smart Money, Congressional Trades & Institutional Options Flow Engine."""

from typing import List, Dict, Any

CONGRESSIONAL_TRADES: List[Dict[str, Any]] = [
    {
        "id": "cong-nvda-1",
        "politician": "Nancy Pelosi (D-CA)",
        "chamber": "House",
        "ticker": "NVDA",
        "asset_name": "NVIDIA Corporation",
        "transaction_type": "Purchase (Call Options)",
        "amount_range": "$1,000,000 - $5,000,000",
        "filing_date": "2026-08-14",
        "transaction_date": "2026-07-28",
        "strike_price": "$180 Calls",
        "days_to_filing": 17,
        "performance_since_pct": 14.8,
        "sentiment": "Strong Bullish",
        "details": {
            "committee_assignments": ["Former Speaker", "House Democratic Leadership", "Appropriations (Prior)"],
            "legislative_conflict_thesis": "Strategic timing ahead of federal AI compute export rule revisions and next-generation datacenter infrastructure appropriations.",
            "historical_win_rate_pct": 78.5,
            "annualized_tech_alpha_pct": 34.2,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Filed within statutory 45-day window (17 days lag).",
            "key_catalyst": "Massive sovereign AI datacenter orders and enterprise Rubin GPU ramp.",
        },
    },
    {
        "id": "cong-nvo-1",
        "politician": "Michael McCaul (R-TX)",
        "chamber": "House",
        "ticker": "NVO",
        "asset_name": "Novo Nordisk A/S",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$250,000 - $500,000",
        "filing_date": "2026-08-18",
        "transaction_date": "2026-08-02",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 16,
        "performance_since_pct": 6.4,
        "sentiment": "Strong Bullish",
        "details": {
            "committee_assignments": ["Foreign Affairs Committee (Chairman)", "Homeland Security"],
            "legislative_conflict_thesis": "Transatlantic pharmaceutical supply chain discussions and federal healthcare Medicare GLP-1 reimbursement expansion deliberations.",
            "historical_win_rate_pct": 71.0,
            "annualized_tech_alpha_pct": 22.8,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Filed within statutory 45-day window (16 days lag).",
            "key_catalyst": "Phase 3 Amycretin oral pill clinical readout and Catalent fill-finish manufacturing expansion.",
        },
    },
    {
        "id": "cong-lly-1",
        "politician": "Tommy Tuberville (R-AL)",
        "chamber": "Senate",
        "ticker": "LLY",
        "asset_name": "Eli Lilly & Co.",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$100,000 - $250,000",
        "filing_date": "2026-08-20",
        "transaction_date": "2026-08-05",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 15,
        "performance_since_pct": 5.2,
        "sentiment": "Bullish",
        "details": {
            "committee_assignments": ["Senate Armed Services", "Agriculture, Nutrition & Forestry", "Veterans' Affairs"],
            "legislative_conflict_thesis": "VA healthcare system drug formulary inclusion and domestic pharmaceutical manufacturing tax incentives.",
            "historical_win_rate_pct": 64.5,
            "annualized_tech_alpha_pct": 18.4,
            "source_filing_url": "https://efdsearch.senate.gov",
            "stock_act_compliance": "Filed within statutory 45-day window (15 days lag).",
            "key_catalyst": "Retatrutide Phase 3 triple-hormone agonist weight loss trial readouts.",
        },
    },
    {
        "id": "cong-msft-1",
        "politician": "Ro Khanna (D-CA)",
        "chamber": "House",
        "ticker": "MSFT",
        "asset_name": "Microsoft Corp.",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$500,000 - $1,000,000",
        "filing_date": "2026-08-15",
        "transaction_date": "2026-07-30",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 16,
        "performance_since_pct": 3.8,
        "sentiment": "Bullish",
        "details": {
            "committee_assignments": ["Armed Services (Cyber & Innovative Technologies)", "Oversight & Accountability"],
            "legislative_conflict_thesis": "Federal Department of Defense enterprise cloud modernization and cybersecurity contract renewal cycles.",
            "historical_win_rate_pct": 69.2,
            "annualized_tech_alpha_pct": 21.5,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Filed within statutory 45-day window (16 days lag).",
            "key_catalyst": "Azure OpenAI enterprise copilot ARR expansion and Pentagon multi-cloud contract deployments.",
        },
    },
    {
        "id": "cong-pltr-1",
        "politician": "Dan Crenshaw (R-TX)",
        "chamber": "House",
        "ticker": "PLTR",
        "asset_name": "Palantir Technologies",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$50,000 - $100,000",
        "filing_date": "2026-08-22",
        "transaction_date": "2026-08-10",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 12,
        "performance_since_pct": 12.1,
        "sentiment": "Strong Bullish",
        "details": {
            "committee_assignments": ["Energy & Commerce", "House Permanent Select Committee on Intelligence"],
            "legislative_conflict_thesis": "Direct oversight of intelligence community software procurement and defense AI telemetry systems.",
            "historical_win_rate_pct": 74.0,
            "annualized_tech_alpha_pct": 29.4,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Rapid filing within 12 days of execution.",
            "key_catalyst": "AIP platform commercial bootcamps conversion and US Army TITAN contract ramp.",
        },
    },
    {
        "id": "cong-aapl-1",
        "politician": "Josh Gottheimer (D-NJ)",
        "chamber": "House",
        "ticker": "AAPL",
        "asset_name": "Apple Inc.",
        "transaction_type": "Sale (Partial)",
        "amount_range": "$100,000 - $250,000",
        "filing_date": "2026-08-10",
        "transaction_date": "2026-07-25",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 16,
        "performance_since_pct": -1.2,
        "sentiment": "Neutral / Profit Take",
        "details": {
            "committee_assignments": ["Financial Services (Capital Markets)", "House Permanent Select Committee on Intelligence"],
            "legislative_conflict_thesis": "Rebalancing portfolio risk ahead of antitrust deliberations on mobile app store fee structures.",
            "historical_win_rate_pct": 66.8,
            "annualized_tech_alpha_pct": 16.2,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Routine disclosure filing within standard lag window.",
            "key_catalyst": "Services margin expansion vs hardware replacement cycle velocity.",
        },
    },
]

UNUSUAL_OPTIONS_FLOW: List[Dict[str, Any]] = [
    {
        "id": "opt-nvda-1",
        "time": "10:42:15",
        "ticker": "NVDA",
        "type": "CALL SWEEP",
        "strike": "$220.00",
        "expiration": "2026-09-18",
        "spot_price": 213.05,
        "premium": "$3,450,000",
        "volume_oi_ratio": 4.85,
        "implied_volatility": "44.2%",
        "order_type": "Ask (Aggressive Buying)",
        "sentiment": "Strong Bullish",
        "details": {
            "execution_urgency": "High (Executed across 6 options exchanges simultaneously)",
            "strike_distance_pct": 3.26,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.42,
            "gamma_pin_level": "$220.00 strike concentration",
            "open_interest_before": 1240,
            "volume_today": 6014,
            "institutional_intent": "Speculative breakout positioning ahead of institutional tech conference and forward guidance revisions.",
            "market_maker_hedging_impact": "Positive Gamma forcing market makers to buy underlying shares on upward momentum.",
        },
    },
    {
        "id": "opt-nvo-1",
        "time": "10:38:40",
        "ticker": "NVO",
        "type": "CALL BLOCK",
        "strike": "$145.00",
        "expiration": "2026-10-16",
        "spot_price": 138.50,
        "premium": "$1,820,000",
        "volume_oi_ratio": 3.42,
        "implied_volatility": "32.8%",
        "order_type": "Above Ask (High Urgency)",
        "sentiment": "Strong Bullish",
        "details": {
            "execution_urgency": "Extreme (Buyer paid above prevailing ask price to guarantee single-print fill)",
            "strike_distance_pct": 4.69,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.38,
            "gamma_pin_level": "$145.00 major resistance magnet",
            "open_interest_before": 2100,
            "volume_today": 7182,
            "institutional_intent": "High-conviction positioning on Phase 3 oral GLP-1 readout milestones.",
            "market_maker_hedging_impact": "Accelerating delta hedging required if spot crosses $140 threshold.",
        },
    },
    {
        "id": "opt-tsla-1",
        "time": "10:31:05",
        "ticker": "TSLA",
        "type": "PUT SWEEP",
        "strike": "$330.00",
        "expiration": "2026-08-28",
        "spot_price": 350.25,
        "premium": "$2,150,000",
        "volume_oi_ratio": 5.12,
        "implied_volatility": "58.4%",
        "order_type": "Bid (Aggressive Hedging)",
        "sentiment": "Bearish / Tail Hedge",
        "details": {
            "execution_urgency": "High (Rapid multi-exchange liquidity sweep)",
            "strike_distance_pct": -5.78,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": -0.31,
            "gamma_pin_level": "$330.00 downside support floor",
            "open_interest_before": 3400,
            "volume_today": 17400,
            "institutional_intent": "Short-term downside protection or volatility arbitrage against delivery figures.",
            "market_maker_hedging_impact": "Negative gamma zone accelerating selling if $345 support breaks.",
        },
    },
    {
        "id": "opt-spy-1",
        "time": "10:24:50",
        "ticker": "SPY",
        "type": "DARK POOL BLOCK",
        "strike": "Spot Equity",
        "expiration": "N/A",
        "spot_price": 765.91,
        "premium": "$48,200,000",
        "volume_oi_ratio": 2.10,
        "implied_volatility": "14.5%",
        "order_type": "Cross Trade (Off-Exchange OTC)",
        "sentiment": "Institutional Inflow",
        "details": {
            "execution_urgency": "Institutional Sizing ($48.2M single dark pool print)",
            "strike_distance_pct": 0.0,
            "moneyness": "At-the-Market",
            "delta_est": 1.0,
            "gamma_pin_level": "$765.00 broad index pivot",
            "open_interest_before": 0,
            "volume_today": 62900,
            "institutional_intent": "Passive benchmark rebalancing and systematic sovereign fund liquidity allocation.",
            "market_maker_hedging_impact": "Neutralizing off-exchange volatility.",
        },
    },
    {
        "id": "opt-lly-1",
        "time": "10:15:22",
        "ticker": "LLY",
        "type": "CALL SWEEP",
        "strike": "$950.00",
        "expiration": "2026-11-20",
        "spot_price": 920.40,
        "premium": "$2,640,000",
        "volume_oi_ratio": 3.90,
        "implied_volatility": "28.5%",
        "order_type": "Ask (Aggressive)",
        "sentiment": "Strong Bullish",
        "details": {
            "execution_urgency": "High (Multi-month LEAP accumulation)",
            "strike_distance_pct": 3.22,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.44,
            "gamma_pin_level": "$950.00 institutional magnet",
            "open_interest_before": 1850,
            "volume_today": 7215,
            "institutional_intent": "Long-term institutional accumulation betting on sustained gross margin expansion.",
            "market_maker_hedging_impact": "Steady upward pressure as spot converges toward $950 strike.",
        },
    },
]

class SmartMoneyEngine:
    """Quantitative engine for tracking Capitol Hill disclosures & institutional options flow."""

    @staticmethod
    def get_congressional_trades(symbol: str = None) -> List[Dict[str, Any]]:
        if symbol:
            sym_clean = symbol.upper().strip()
            return [t for t in CONGRESSIONAL_TRADES if t["ticker"] == sym_clean]
        return CONGRESSIONAL_TRADES

    @staticmethod
    def get_options_flow(symbol: str = None) -> List[Dict[str, Any]]:
        if symbol:
            sym_clean = symbol.upper().strip()
            return [f for f in UNUSUAL_OPTIONS_FLOW if f["ticker"] == sym_clean]
        return UNUSUAL_OPTIONS_FLOW

    @staticmethod
    def get_smart_money_overview() -> Dict[str, Any]:
        return {
            "total_congress_filings_30d": len(CONGRESSIONAL_TRADES),
            "net_political_sentiment": "Bullish (83.3% Purchases)",
            "top_congress_bought_sector": "Semiconductors & GLP-1 Healthcare",
            "unusual_flow_volume_today": "$58.2M",
            "call_to_put_dollar_ratio": 2.85,
            "congress_trades": CONGRESSIONAL_TRADES,
            "options_flow": UNUSUAL_OPTIONS_FLOW,
        }
