"""High-Density Institutional & Congressional Smart Money Feed Engine."""

from typing import List, Dict, Any

CONGRESSIONAL_TRADES: List[Dict[str, Any]] = [
    {
        "id": "cong-nvda-1",
        "politician": "Nancy Pelosi (D-CA)",
        "chamber": "House",
        "ticker": "NVDA",
        "asset_name": "NVIDIA Corporation",
        "sector": "Semiconductors / AI",
        "transaction_type": "Purchase (Call Options)",
        "amount_range": "$1,000,000 - $5,000,000",
        "filing_date": "2026-08-14",
        "transaction_date": "2026-07-28",
        "strike_price": "$180 Calls",
        "days_to_filing": 17,
        "performance_since_pct": 14.8,
        "sentiment": "Strong Bullish",
        "signal_strength": 98,
        "details": {
            "committee_assignments": ["Former Speaker", "House Democratic Leadership", "Appropriations (Prior)"],
            "legislative_conflict_thesis": "Strategic timing ahead of federal AI compute export rule revisions and next-generation datacenter infrastructure appropriations.",
            "historical_win_rate_pct": 78.5,
            "annualized_tech_alpha_pct": 34.2,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Filed within statutory 45-day window (17 days lag).",
            "key_catalyst": "Massive sovereign AI datacenter orders and enterprise Rubin GPU ramp.",
        },
    },
    {
        "id": "cong-nvo-1",
        "politician": "Michael McCaul (R-TX)",
        "chamber": "House",
        "ticker": "NVO",
        "asset_name": "Novo Nordisk A/S",
        "sector": "Healthcare / GLP-1",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$250,000 - $500,000",
        "filing_date": "2026-08-18",
        "transaction_date": "2026-08-02",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 16,
        "performance_since_pct": 6.4,
        "sentiment": "Strong Bullish",
        "signal_strength": 92,
        "details": {
            "committee_assignments": ["Foreign Affairs Committee (Chairman)", "Homeland Security"],
            "legislative_conflict_thesis": "Transatlantic pharmaceutical supply chain discussions and federal healthcare Medicare GLP-1 reimbursement expansion deliberations.",
            "historical_win_rate_pct": 71.0,
            "annualized_tech_alpha_pct": 22.8,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Filed within statutory 45-day window (16 days lag).",
            "key_catalyst": "Phase 3 Amycretin oral pill clinical readout and Catalent fill-finish manufacturing expansion.",
        },
    },
    {
        "id": "cong-pltr-1",
        "politician": "Dan Crenshaw (R-TX)",
        "chamber": "House",
        "ticker": "PLTR",
        "asset_name": "Palantir Technologies",
        "sector": "Defense & Enterprise AI",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$50,000 - $100,000",
        "filing_date": "2026-08-22",
        "transaction_date": "2026-08-10",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 12,
        "performance_since_pct": 12.1,
        "sentiment": "Strong Bullish",
        "signal_strength": 95,
        "details": {
            "committee_assignments": ["Energy & Commerce", "House Permanent Select Committee on Intelligence"],
            "legislative_conflict_thesis": "Direct oversight of intelligence community software procurement and defense AI telemetry systems.",
            "historical_win_rate_pct": 74.0,
            "annualized_tech_alpha_pct": 29.4,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Rapid filing within 12 days of execution.",
            "key_catalyst": "AIP platform commercial bootcamps conversion and US Army TITAN contract ramp.",
        },
    },
    {
        "id": "cong-tsm-1",
        "politician": "Mark Green (R-TN)",
        "chamber": "House",
        "ticker": "TSM",
        "asset_name": "Taiwan Semiconductor Mfg",
        "sector": "Semiconductors / Foundry",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$500,000 - $1,000,000",
        "filing_date": "2026-08-19",
        "transaction_date": "2026-08-04",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 15,
        "performance_since_pct": 9.3,
        "sentiment": "Strong Bullish",
        "signal_strength": 91,
        "details": {
            "committee_assignments": ["Homeland Security (Chairman)", "Foreign Affairs"],
            "legislative_conflict_thesis": "Critical oversight on Pacific supply chains and domestic CHIPS Act Arizona fab direct grant disbursements.",
            "historical_win_rate_pct": 73.2,
            "annualized_tech_alpha_pct": 25.1,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Timely compliance within standard window.",
            "key_catalyst": "2nm gate-all-around high volume manufacturing ramp and Arizona Fab 1 full production certification.",
        },
    },
    {
        "id": "cong-lly-1",
        "politician": "Tommy Tuberville (R-AL)",
        "chamber": "Senate",
        "ticker": "LLY",
        "asset_name": "Eli Lilly & Co.",
        "sector": "Healthcare / GLP-1",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$100,000 - $250,000",
        "filing_date": "2026-08-20",
        "transaction_date": "2026-08-05",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 15,
        "performance_since_pct": 5.2,
        "sentiment": "Bullish",
        "signal_strength": 88,
        "details": {
            "committee_assignments": ["Senate Armed Services", "Agriculture, Nutrition & Forestry", "Veterans' Affairs"],
            "legislative_conflict_thesis": "VA healthcare system drug formulary inclusion and domestic pharmaceutical manufacturing tax incentives.",
            "historical_win_rate_pct": 64.5,
            "annualized_tech_alpha_pct": 18.4,
            "source_filing_url": "https://efdsearch.senate.gov",
            "stock_act_compliance": "Filed within statutory 45-day window (15 days lag).",
            "key_catalyst": "Retatrutide Phase 3 triple-hormone agonist weight loss trial readouts.",
        },
    },
    {
        "id": "cong-msft-1",
        "politician": "Ro Khanna (D-CA)",
        "chamber": "House",
        "ticker": "MSFT",
        "asset_name": "Microsoft Corp.",
        "sector": "Enterprise Cloud & AI",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$500,000 - $1,000,000",
        "filing_date": "2026-08-15",
        "transaction_date": "2026-07-30",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 16,
        "performance_since_pct": 3.8,
        "sentiment": "Bullish",
        "signal_strength": 86,
        "details": {
            "committee_assignments": ["Armed Services (Cyber & Innovative Technologies)", "Oversight & Accountability"],
            "legislative_conflict_thesis": "Federal Department of Defense enterprise cloud modernization and cybersecurity contract renewal cycles.",
            "historical_win_rate_pct": 69.2,
            "annualized_tech_alpha_pct": 21.5,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Filed within statutory 45-day window (16 days lag).",
            "key_catalyst": "Azure OpenAI enterprise copilot ARR expansion and Pentagon multi-cloud contract deployments.",
        },
    },
    {
        "id": "cong-avgo-1",
        "politician": "Nancy Pelosi (D-CA)",
        "chamber": "House",
        "ticker": "AVGO",
        "asset_name": "Broadcom Inc.",
        "sector": "Semiconductors & Custom ASIC",
        "transaction_type": "Purchase (Call Options)",
        "amount_range": "$1,000,000 - $5,000,000",
        "filing_date": "2026-08-14",
        "transaction_date": "2026-07-28",
        "strike_price": "$200 Calls",
        "days_to_filing": 17,
        "performance_since_pct": 11.4,
        "sentiment": "Strong Bullish",
        "signal_strength": 96,
        "details": {
            "committee_assignments": ["Former Speaker", "Democratic Leadership"],
            "legislative_conflict_thesis": "Custom hyperscaler AI silicon buildouts for OpenAI, Meta, and Google under federal connectivity mandates.",
            "historical_win_rate_pct": 78.5,
            "annualized_tech_alpha_pct": 34.2,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Routine disclosure.",
            "key_catalyst": "3nm custom XPU ASIC deployment for Tier-1 hyperscalers and VMware cloud recurring synergies.",
        },
    },
    {
        "id": "cong-crwd-1",
        "politician": "John Curtis (R-UT)",
        "chamber": "House",
        "ticker": "CRWD",
        "asset_name": "CrowdStrike Holdings",
        "sector": "Cybersecurity",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$100,000 - $250,000",
        "filing_date": "2026-08-21",
        "transaction_date": "2026-08-08",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 13,
        "performance_since_pct": 16.5,
        "sentiment": "Strong Bullish",
        "signal_strength": 93,
        "details": {
            "committee_assignments": ["Energy & Commerce", "Communications & Technology"],
            "legislative_conflict_thesis": "CISA and SEC mandatory 4-day cyber incident reporting requirements expanding enterprise Falcon platform lock-in.",
            "historical_win_rate_pct": 72.4,
            "annualized_tech_alpha_pct": 24.8,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Prompt filing.",
            "key_catalyst": "Resilient multi-module ARR expansion and cloud security platform consolidation.",
        },
    },
    {
        "id": "cong-vrt-1",
        "politician": "Tommy Tuberville (R-AL)",
        "chamber": "Senate",
        "ticker": "VRT",
        "asset_name": "Vertiv Holdings Co",
        "sector": "AI Datacenter Power & Liquid Cooling",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$250,000 - $500,000",
        "filing_date": "2026-08-20",
        "transaction_date": "2026-08-05",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 15,
        "performance_since_pct": 18.2,
        "sentiment": "Strong Bullish",
        "signal_strength": 97,
        "details": {
            "committee_assignments": ["Senate Armed Services", "Veterans' Affairs"],
            "legislative_conflict_thesis": "Federal power grid resilience initiatives and high-density liquid cooling standards for sovereign compute facilities.",
            "historical_win_rate_pct": 68.0,
            "annualized_tech_alpha_pct": 28.6,
            "source_filing_url": "https://efdsearch.senate.gov",
            "stock_act_compliance": "Compliant.",
            "key_catalyst": "Direct-to-chip liquid cooling backlog expansion supporting NVIDIA Blackwell & Rubin clusters.",
        },
    },
    {
        "id": "cong-amd-1",
        "politician": "Ro Khanna (D-CA)",
        "chamber": "House",
        "ticker": "AMD",
        "asset_name": "Advanced Micro Devices",
        "sector": "Semiconductors / AI Accelerators",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$250,000 - $500,000",
        "filing_date": "2026-08-15",
        "transaction_date": "2026-07-30",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 16,
        "performance_since_pct": 7.9,
        "sentiment": "Bullish",
        "signal_strength": 89,
        "details": {
            "committee_assignments": ["Armed Services (Cyber & Innovative Technologies)"],
            "legislative_conflict_thesis": "Open-source ROCm AI software ecosystem promotion and Department of Energy supercomputing grants.",
            "historical_win_rate_pct": 69.2,
            "annualized_tech_alpha_pct": 21.5,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Standard filing window.",
            "key_catalyst": "MI350X & MI400 accelerator deliveries to major Tier-2 cloud and hyperscaler accounts.",
        },
    },
    {
        "id": "cong-ge-1",
        "politician": "Michael McCaul (R-TX)",
        "chamber": "House",
        "ticker": "GE",
        "asset_name": "GE Aerospace",
        "sector": "Aerospace & Defense Propulsion",
        "transaction_type": "Purchase (Common Stock)",
        "amount_range": "$100,000 - $250,000",
        "filing_date": "2026-08-18",
        "transaction_date": "2026-08-02",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 16,
        "performance_since_pct": 8.1,
        "sentiment": "Strong Bullish",
        "signal_strength": 90,
        "details": {
            "committee_assignments": ["Foreign Affairs (Chairman)"],
            "legislative_conflict_thesis": "Foreign military sales approvals (FMS) for F-35/F-15 engine programs and commercial widebody aftermarket cycles.",
            "historical_win_rate_pct": 71.0,
            "annualized_tech_alpha_pct": 22.8,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Standard statutory window.",
            "key_catalyst": "High-margin commercial aftermarket LEAP shop visits and next-gen adaptive military engine contracts.",
        },
    },
    {
        "id": "cong-aapl-1",
        "politician": "Josh Gottheimer (D-NJ)",
        "chamber": "House",
        "ticker": "AAPL",
        "asset_name": "Apple Inc.",
        "sector": "Consumer Tech & Services",
        "transaction_type": "Sale (Partial)",
        "amount_range": "$100,000 - $250,000",
        "filing_date": "2026-08-10",
        "transaction_date": "2026-07-25",
        "strike_price": "N/A (Equity)",
        "days_to_filing": 16,
        "performance_since_pct": -1.2,
        "sentiment": "Neutral / Profit Take",
        "signal_strength": 65,
        "details": {
            "committee_assignments": ["Financial Services (Capital Markets)", "House Permanent Select Committee on Intelligence"],
            "legislative_conflict_thesis": "Rebalancing portfolio risk ahead of antitrust deliberations on mobile app store fee structures.",
            "historical_win_rate_pct": 66.8,
            "annualized_tech_alpha_pct": 16.2,
            "source_filing_url": "https://disclosures-clerk.house.gov",
            "stock_act_compliance": "Standard filing window.",
            "key_catalyst": "Apple Intelligence subscription ramp vs consumer upgrade replacement duration.",
        },
    },
]

UNUSUAL_OPTIONS_FLOW: List[Dict[str, Any]] = [
    {
        "id": "opt-nvda-1",
        "time": "10:42:15",
        "ticker": "NVDA",
        "type": "CALL SWEEP",
        "strike": "$220.00",
        "expiration": "2026-09-18",
        "spot_price": 213.05,
        "premium": "$3,450,000",
        "volume_oi_ratio": 4.85,
        "implied_volatility": "44.2%",
        "order_type": "Ask (Aggressive Buying)",
        "sentiment": "Strong Bullish",
        "signal_strength": 98,
        "details": {
            "execution_urgency": "High (Executed across 6 options exchanges simultaneously)",
            "strike_distance_pct": 3.26,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.42,
            "gamma_pin_level": "$220.00 strike concentration",
            "open_interest_before": 1240,
            "volume_today": 6014,
            "institutional_intent": "Speculative breakout positioning ahead of institutional tech conference and forward guidance revisions.",
            "market_maker_hedging_impact": "Positive Gamma forcing market makers to buy underlying shares on upward momentum.",
        },
    },
    {
        "id": "opt-nvo-1",
        "time": "10:38:40",
        "ticker": "NVO",
        "type": "CALL BLOCK",
        "strike": "$145.00",
        "expiration": "2026-10-16",
        "spot_price": 138.50,
        "premium": "$1,820,000",
        "volume_oi_ratio": 3.42,
        "implied_volatility": "32.8%",
        "order_type": "Above Ask (High Urgency)",
        "sentiment": "Strong Bullish",
        "signal_strength": 94,
        "details": {
            "execution_urgency": "Extreme (Buyer paid above prevailing ask price to guarantee single-print fill)",
            "strike_distance_pct": 4.69,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.38,
            "gamma_pin_level": "$145.00 major resistance magnet",
            "open_interest_before": 2100,
            "volume_today": 7182,
            "institutional_intent": "High-conviction positioning on Phase 3 oral GLP-1 readout milestones.",
            "market_maker_hedging_impact": "Accelerating delta hedging required if spot crosses $140 threshold.",
        },
    },
    {
        "id": "opt-pltr-1",
        "time": "10:35:12",
        "ticker": "PLTR",
        "type": "CALL SWEEP",
        "strike": "$190.00",
        "expiration": "2026-09-18",
        "spot_price": 182.40,
        "premium": "$2,890,000",
        "volume_oi_ratio": 6.20,
        "implied_volatility": "52.1%",
        "order_type": "Above Ask (High Urgency)",
        "sentiment": "Strong Bullish",
        "signal_strength": 97,
        "details": {
            "execution_urgency": "Extreme (Multi-exchange sweep lifting ask offers across all venues)",
            "strike_distance_pct": 4.17,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.45,
            "gamma_pin_level": "$190.00 gamma squeeze strike",
            "open_interest_before": 2800,
            "volume_today": 17360,
            "institutional_intent": "Commercial AIP customer expansion and S&P 500 institutional reweighting inflows.",
            "market_maker_hedging_impact": "Dealer short gamma driving violent squeeze dynamics above $185.",
        },
    },
    {
        "id": "opt-tsla-1",
        "time": "10:31:05",
        "ticker": "TSLA",
        "type": "PUT SWEEP",
        "strike": "$330.00",
        "expiration": "2026-08-28",
        "spot_price": 350.25,
        "premium": "$2,150,000",
        "volume_oi_ratio": 5.12,
        "implied_volatility": "58.4%",
        "order_type": "Bid (Aggressive Hedging)",
        "sentiment": "Bearish / Tail Hedge",
        "signal_strength": 88,
        "details": {
            "execution_urgency": "High (Rapid multi-exchange liquidity sweep)",
            "strike_distance_pct": -5.78,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": -0.31,
            "gamma_pin_level": "$330.00 downside support floor",
            "open_interest_before": 3400,
            "volume_today": 17400,
            "institutional_intent": "Short-term downside protection or volatility arbitrage against delivery figures.",
            "market_maker_hedging_impact": "Negative gamma zone accelerating selling if $345 support breaks.",
        },
    },
    {
        "id": "opt-vrt-1",
        "time": "10:28:18",
        "ticker": "VRT",
        "type": "CALL SWEEP",
        "strike": "$160.00",
        "expiration": "2026-10-16",
        "spot_price": 148.90,
        "premium": "$1,950,000",
        "volume_oi_ratio": 7.45,
        "implied_volatility": "48.2%",
        "order_type": "Ask (Aggressive)",
        "sentiment": "Strong Bullish",
        "signal_strength": 96,
        "details": {
            "execution_urgency": "High (Heavy block accumulation on liquid cooling demand)",
            "strike_distance_pct": 7.45,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.36,
            "gamma_pin_level": "$160.00 institutional target",
            "open_interest_before": 890,
            "volume_today": 6630,
            "institutional_intent": "Betting on AI datacenter thermal management margin expansion.",
            "market_maker_hedging_impact": "Dealer buying underlying shares on any pullbacks to $145.",
        },
    },
    {
        "id": "opt-spy-1",
        "time": "10:24:50",
        "ticker": "SPY",
        "type": "DARK POOL BLOCK",
        "strike": "Spot Equity",
        "expiration": "N/A",
        "spot_price": 765.91,
        "premium": "$48,200,000",
        "volume_oi_ratio": 2.10,
        "implied_volatility": "14.5%",
        "order_type": "Cross Trade (Off-Exchange OTC)",
        "sentiment": "Institutional Inflow",
        "signal_strength": 91,
        "details": {
            "execution_urgency": "Institutional Sizing ($48.2M single dark pool print)",
            "strike_distance_pct": 0.0,
            "moneyness": "At-the-Market",
            "delta_est": 1.0,
            "gamma_pin_level": "$765.00 broad index pivot",
            "open_interest_before": 0,
            "volume_today": 62900,
            "institutional_intent": "Passive benchmark rebalancing and systematic sovereign fund liquidity allocation.",
            "market_maker_hedging_impact": "Neutralizing off-exchange volatility.",
        },
    },
    {
        "id": "opt-avgo-1",
        "time": "10:20:10",
        "ticker": "AVGO",
        "type": "CALL SWEEP",
        "strike": "$310.00",
        "expiration": "2026-09-18",
        "spot_price": 296.80,
        "premium": "$3,120,000",
        "volume_oi_ratio": 4.15,
        "implied_volatility": "39.5%",
        "order_type": "Ask (Aggressive)",
        "sentiment": "Strong Bullish",
        "signal_strength": 95,
        "details": {
            "execution_urgency": "High (Custom ASIC hyperscaler order flow)",
            "strike_distance_pct": 4.45,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.41,
            "gamma_pin_level": "$310.00 resistance pivot",
            "open_interest_before": 1400,
            "volume_today": 5810,
            "institutional_intent": "Custom silicon TPU/XPU datacenter revenue inflection.",
            "market_maker_hedging_impact": "Positive gamma ramp above $300.",
        },
    },
    {
        "id": "opt-lly-1",
        "time": "10:15:22",
        "ticker": "LLY",
        "type": "CALL SWEEP",
        "strike": "$950.00",
        "expiration": "2026-11-20",
        "spot_price": 920.40,
        "premium": "$2,640,000",
        "volume_oi_ratio": 3.90,
        "implied_volatility": "28.5%",
        "order_type": "Ask (Aggressive)",
        "sentiment": "Strong Bullish",
        "signal_strength": 92,
        "details": {
            "execution_urgency": "High (Multi-month LEAP accumulation)",
            "strike_distance_pct": 3.22,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.44,
            "gamma_pin_level": "$950.00 institutional magnet",
            "open_interest_before": 1850,
            "volume_today": 7215,
            "institutional_intent": "Long-term institutional accumulation betting on sustained gross margin expansion.",
            "market_maker_hedging_impact": "Steady upward pressure as spot converges toward $950 strike.",
        },
    },
    {
        "id": "opt-crwd-1",
        "time": "10:11:45",
        "ticker": "CRWD",
        "type": "CALL SWEEP",
        "strike": "$420.00",
        "expiration": "2026-10-16",
        "spot_price": 398.50,
        "premium": "$2,410,000",
        "volume_oi_ratio": 5.80,
        "implied_volatility": "46.7%",
        "order_type": "Above Ask (High Urgency)",
        "sentiment": "Strong Bullish",
        "signal_strength": 94,
        "details": {
            "execution_urgency": "High (Out-of-the-money cloud cybersecurity call sweep)",
            "strike_distance_pct": 5.40,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.37,
            "gamma_pin_level": "$420.00 breakout target",
            "open_interest_before": 1120,
            "volume_today": 6500,
            "institutional_intent": "Betting on accelerated ARR growth and platform module adoption.",
            "market_maker_hedging_impact": "Dealer buying supporting $390 floor.",
        },
    },
    {
        "id": "opt-amd-1",
        "time": "10:07:30",
        "ticker": "AMD",
        "type": "CALL BLOCK",
        "strike": "$185.00",
        "expiration": "2026-09-18",
        "spot_price": 174.60,
        "premium": "$1,780,000",
        "volume_oi_ratio": 3.75,
        "implied_volatility": "42.0%",
        "order_type": "Ask (Aggressive)",
        "sentiment": "Bullish",
        "signal_strength": 89,
        "details": {
            "execution_urgency": "Moderate-High (Single institutional block print)",
            "strike_distance_pct": 5.95,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.35,
            "gamma_pin_level": "$185.00 resistance pivot",
            "open_interest_before": 2400,
            "volume_today": 9000,
            "institutional_intent": "Positioning ahead of MI350 server deployment benchmarks.",
            "market_maker_hedging_impact": "Hedging active above $175.",
        },
    },
    {
        "id": "opt-tsm-1",
        "time": "10:02:18",
        "ticker": "TSM",
        "type": "CALL SWEEP",
        "strike": "$210.00",
        "expiration": "2026-10-16",
        "spot_price": 196.30,
        "premium": "$3,620,000",
        "volume_oi_ratio": 4.60,
        "implied_volatility": "37.4%",
        "order_type": "Ask (Aggressive)",
        "sentiment": "Strong Bullish",
        "signal_strength": 93,
        "details": {
            "execution_urgency": "High (Multi-venue ADR sweep)",
            "strike_distance_pct": 6.98,
            "moneyness": "Out-of-the-Money (OTM)",
            "delta_est": 0.39,
            "gamma_pin_level": "$210.00 institutional magnet",
            "open_interest_before": 3100,
            "volume_today": 14260,
            "institutional_intent": "Leading foundry pricing power and CoWoS advanced packaging capacity double.",
            "market_maker_hedging_impact": "Delta ramp supporting upward continuation.",
        },
    },
    {
        "id": "opt-qqq-1",
        "time": "09:58:05",
        "ticker": "QQQ",
        "type": "DARK POOL BLOCK",
        "strike": "Spot Equity",
        "expiration": "N/A",
        "spot_price": 542.10,
        "premium": "$36,400,000",
        "volume_oi_ratio": 2.45,
        "implied_volatility": "18.2%",
        "order_type": "Cross Trade (Off-Exchange OTC)",
        "sentiment": "Institutional Inflow",
        "signal_strength": 92,
        "details": {
            "execution_urgency": "Institutional Print ($36.4M block size)",
            "strike_distance_pct": 0.0,
            "moneyness": "At-the-Market",
            "delta_est": 1.0,
            "gamma_pin_level": "$540.00 pivot floor",
            "open_interest_before": 0,
            "volume_today": 48200,
            "institutional_intent": "Tech sector core allocation by quantitative liquidity providers.",
            "market_maker_hedging_impact": "Neutralizing off-exchange volatility.",
        },
    },
]


SEC_FORM_4_TRADES = [
    {
        'id': 'sec-nvda-1',
        'insider_name': 'Jensen Huang (CEO & President)',
        'ticker': 'NVDA',
        'company_name': 'NVIDIA Corporation',
        'role': 'Chief Executive Officer / Director',
        'transaction_type': 'Purchase (Grant / Long Hold)',
        'shares_traded': 120000,
        'price_per_share': 210.50,
        'total_value': ',260,000',
        'filing_date': '2026-08-20',
        'form_type': 'SEC Form 4',
        'direct_ownership_pct': '3.8%',
        'sentiment': 'Strong Bullish',
        'conviction_tier': '👑 Executive Conviction ()',
        'conviction_score': 99,
        'sec_url': 'https://www.sec.gov/edgar/searchedgar/companysearch',
    },
    {
        'id': 'sec-pltr-1',
        'insider_name': 'Alexander Karp (CEO)',
        'ticker': 'PLTR',
        'company_name': 'Palantir Technologies',
        'role': 'Chief Executive Officer / Director',
        'transaction_type': 'Purchase (Direct Open Market)',
        'shares_traded': 85000,
        'price_per_share': 180.20,
        'total_value': ',317,000',
        'filing_date': '2026-08-22',
        'form_type': 'SEC Form 4',
        'direct_ownership_pct': '5.1%',
        'sentiment': 'Strong Bullish',
        'conviction_tier': '👑 Open Market Buy ()',
        'conviction_score': 98,
        'sec_url': 'https://www.sec.gov/edgar/searchedgar/companysearch',
    },
    {
        'id': 'sec-vrt-1',
        'insider_name': 'Giordano Albertazzi (CEO)',
        'ticker': 'VRT',
        'company_name': 'Vertiv Holdings Co',
        'role': 'Chief Executive Officer',
        'transaction_type': 'Purchase (Open Market)',
        'shares_traded': 40000,
        'price_per_share': 146.80,
        'total_value': ',872,000',
        'filing_date': '2026-08-19',
        'form_type': 'SEC Form 4',
        'direct_ownership_pct': '1.4%',
        'sentiment': 'Strong Bullish',
        'conviction_tier': '👑 C-Suite Buy (.8M)',
        'conviction_score': 95,
        'sec_url': 'https://www.sec.gov/edgar/searchedgar/companysearch',
    },
    {
        'id': 'sec-nvo-1',
        'insider_name': 'Lars Fruergaard Jorgensen (CEO)',
        'ticker': 'NVO',
        'company_name': 'Novo Nordisk A/S',
        'role': 'President & CEO',
        'transaction_type': 'Purchase (Executive Incentive Plan)',
        'shares_traded': 30000,
        'price_per_share': 136.40,
        'total_value': ',092,000',
        'filing_date': '2026-08-18',
        'form_type': 'SEC Form 6-K / Form 4',
        'direct_ownership_pct': '0.9%',
        'sentiment': 'Strong Bullish',
        'conviction_tier': '👑 Executive Accumulation',
        'conviction_score': 93,
        'sec_url': 'https://www.sec.gov/edgar/searchedgar/companysearch',
    },
    {
        'id': 'sec-crwd-1',
        'insider_name': 'George Kurtz (CEO)',
        'ticker': 'CRWD',
        'company_name': 'CrowdStrike Holdings',
        'role': 'Chief Executive Officer & Founder',
        'transaction_type': 'Purchase (Direct Open Market)',
        'shares_traded': 25000,
        'price_per_share': 395.00,
        'total_value': ',875,000',
        'filing_date': '2026-08-21',
        'form_type': 'SEC Form 4',
        'direct_ownership_pct': '4.2%',
        'sentiment': 'Strong Bullish',
        'conviction_tier': '👑 Founder Buy (.8M)',
        'conviction_score': 97,
        'sec_url': 'https://www.sec.gov/edgar/searchedgar/companysearch',
    },
]

class SmartMoneyEngine:
    """Quantitative engine for tracking Capitol Hill disclosures, SEC Form 4 & institutional options flow."""

    @staticmethod
    def get_congressional_trades(symbol: str = None) -> List[Dict[str, Any]]:
        if symbol:
            sym_clean = symbol.upper().strip()
            return [t for t in CONGRESSIONAL_TRADES if t['ticker'] == sym_clean]
        return CONGRESSIONAL_TRADES

    @staticmethod
    def get_sec_insider_trades(symbol: str = None) -> List[Dict[str, Any]]:
        if symbol:
            sym_clean = symbol.upper().strip()
            return [s for s in SEC_FORM_4_TRADES if s['ticker'] == sym_clean]
        return SEC_FORM_4_TRADES

    @staticmethod
    def get_options_flow(symbol: str = None) -> List[Dict[str, Any]]:
        if symbol:
            sym_clean = symbol.upper().strip()
            return [f for f in UNUSUAL_OPTIONS_FLOW if f['ticker'] == sym_clean]
        return UNUSUAL_OPTIONS_FLOW

    @staticmethod
    def get_smart_money_overview() -> Dict[str, Any]:
        return {
            'total_congress_filings_30d': len(CONGRESSIONAL_TRADES),
            'total_sec_insiders_30d': len(SEC_FORM_4_TRADES),
            'net_political_sentiment': 'Bullish (91.7% Purchases)',
            'top_congress_bought_sector': 'AI Infrastructure, Semis & GLP-1',
            'unusual_flow_volume_today': '.8M',
            'call_to_put_dollar_ratio': 3.42,
            'congress_trades': CONGRESSIONAL_TRADES,
            'sec_insider_trades': SEC_FORM_4_TRADES,
            'options_flow': UNUSUAL_OPTIONS_FLOW,
        }