import {
  DecisionProfile,
  LifecycleStep,
  MentorContext,
  MentorInsight,
  StandardInsightData,
  StandardRecommendationData,
  StandardLearningData,
  StandardEvidenceData,
} from '@/types/ux-foundations';

export const MOCK_DECISION_PROFILE: DecisionProfile = {
  userId: 'pm-inst-042',
  userName: 'Marcus Vance',
  role: 'Lead Quantitative Portfolio Manager',
  qualityScore: 74,
  qualityScoreDelta: 12, // Baseline 62 -> 74
  decileRank: 'Top 18%',
  primaryEdge: 'Institutional Accumulation Setups',
  primaryWeakness: 'Late-Day Momentum Chases',
  activeRulesCount: 12,
  completedDecisionsCount: 142,
  scoreHistory: [
    { date: 'Q3 2025', score: 62, milestone: 'Baseline Audit' },
    { date: 'Q4 2025', score: 64, milestone: 'Flow Filter Enforced' },
    { date: 'Q1 2026', score: 67, milestone: 'Regime Filter V2' },
    { date: 'Q2 2026', score: 71, milestone: 'Stop Discipline Locked' },
    { date: 'Q3 2026', score: 74, milestone: 'Playbook Auto-Pruning' },
  ],
};

export const MOCK_LIFECYCLE_STEPS: LifecycleStep[] = [
  {
    id: 'step-1',
    state: 'OBSERVED',
    label: '1. Observed',
    timestamp: '2026-09-07 09:31:00',
    status: 'COMPLETED',
    actor: 'Flow Aggregator Engine',
    details: 'Catalyst biotech flow volume +2.4σ detected on CPRX',
    durationMs: 420,
  },
  {
    id: 'step-2',
    state: 'PREDICTED',
    label: '2. Predicted',
    timestamp: '2026-09-07 09:31:14',
    status: 'COMPLETED',
    actor: 'Predictive Calibration Engine',
    details: '82% probability of entering Buy Zone within 5 days',
    durationMs: 310,
  },
  {
    id: 'step-3',
    state: 'APPROVED',
    label: '3. Approved',
    timestamp: '2026-09-07 09:32:00',
    status: 'COMPLETED',
    actor: 'Investment Committee Consensus',
    details: 'Quorum reached (4/4 votes). Sizing approved at 3.5% capital floor.',
    durationMs: 1200,
  },
  {
    id: 'step-4',
    state: 'EXECUTING',
    label: '4. Executing',
    timestamp: '2026-09-07 09:35:22',
    status: 'ACTIVE',
    actor: 'Execution Algorithm TWAP',
    details: 'Tranche 1 executed at $24.80. Tranche 2 pending limit $24.65.',
    durationMs: 6400,
  },
  {
    id: 'step-5',
    state: 'RESOLVED',
    label: '5. Resolved',
    timestamp: '2026-09-08 16:00:00',
    status: 'PENDING',
    actor: 'Outcome Auditor',
    details: 'Target resolution date pending expiration window.',
  },
  {
    id: 'step-6',
    state: 'LEARNED',
    label: '6. Learned',
    timestamp: 'Pending Resolution',
    status: 'PENDING',
    actor: 'Attribution Engine',
    details: 'Post-trade factor attribution and bias breakdown.',
  },
  {
    id: 'step-7',
    state: 'PLAYBOOK_UPDATED',
    label: '7. Playbook Updated',
    timestamp: 'Pending Resolution',
    status: 'PENDING',
    actor: 'Playbook Synthesis Engine',
    details: 'Continuous edge reinforcement rule update.',
  },
];

export const MOCK_MENTOR_INSIGHTS: Record<MentorContext, MentorInsight> = {
  ATTENTION: {
    context: 'ATTENTION',
    roleName: 'ARX Attention Coach',
    observation: '3 high-materiality alerts surfaced across 14 watchlist symbols. Noise filter suppressed 19 non-material deltas.',
    understanding: 'CPRX institutional accumulation (+2.4σ flow) is confirmed by sector rotation in Healthcare (+1.8%). High signal-to-noise ratio.',
    recommendation: 'Focus triage on CPRX and NVDA; defer AAPL review until post-session earnings consensus stabilizes.',
    confidence: 94,
    justification: 'Delta Trust Index exceeds 96% with zero false positive threshold breaches over the last 10 sessions.',
    projectedImpact: '+2.8 pts Attention Efficiency',
    evidenceHash: 'c7b56a319f09e81b6a7d5c4e3f2a1b0d8e7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a',
    sampleSize: 84,
    pValue: 0.001,
    tags: ['Triage', 'Materiality Filter', 'Sector Rotation'],
  },
  DECISION: {
    context: 'DECISION',
    roleName: 'ARX Decision Coach',
    observation: 'CPRX entry signal matches your #1 historical edge: Institutional Flow Surge during Stage 2 Consolidation.',
    understanding: 'When entering setups with flow > 2.0σ in low-volatility regimes, your historical win rate is 72.4% with a 2.8 Sharpe.',
    recommendation: 'Execute standard 3.5% allocation with strict trailing stop at $23.90. Do not chase above $25.20.',
    confidence: 91,
    justification: 'Minervini Stage 2 criteria satisfied; volatility compression ratio below 0.45; institutional accumulation verified.',
    projectedImpact: '+4.2 pts Expected Edge',
    evidenceHash: '8f9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f',
    sampleSize: 124,
    pValue: 0.0004,
    tags: ['Minervini Stage 2', 'Position Sizing', 'Stop Discipline'],
  },
  ATTRIBUTION: {
    context: 'ATTRIBUTION',
    roleName: 'ARX Attribution Coach',
    observation: 'Resolved trade on AMD generated +6.4% gain, but exit was triggered 48 hours premature to target.',
    understanding: 'Premature exit was driven by intraday market noise rather than deterioration in the core thesis.',
    recommendation: 'Switch from discretionary intraday trailing stops to end-of-day ATR-based stops on momentum setups.',
    confidence: 88,
    justification: 'Counterfactual simulator reveals +3.1% additional capture on 14 similar momentum trades with daily ATR stops.',
    projectedImpact: '+1.9 pts Sharpe Capture',
    evidenceHash: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2',
    sampleSize: 68,
    pValue: 0.003,
    tags: ['Premature Exit', 'ATR Trail', 'Noise Resistance'],
  },
  LEARNING: {
    context: 'LEARNING',
    roleName: 'ARX Learning Coach',
    observation: 'Your rolling Decision Quality Score increased from 71 to 74 over the past quarter (+12 points from 62 baseline).',
    understanding: 'The largest positive contributor (+6.2 pts) was 91% adherence to Stop Discipline and eliminating Late-Day Momentum Chases.',
    recommendation: 'Target Tier 80 by maintaining strict macro risk hedges during elevated VIX (>22) regimes.',
    confidence: 95,
    justification: 'Behavioral Adoption Rate reached 70.5% with a 43% reduction in repeat mistakes across 142 resolved decisions.',
    projectedImpact: '+6.0 pts to Tier 80 Target',
    evidenceHash: 'd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5',
    sampleSize: 142,
    pValue: 0.0001,
    tags: ['Metacognition', 'Rule Adherence', 'Repeat Mistake Reduction'],
  },
  PLAYBOOK: {
    context: 'PLAYBOOK',
    roleName: 'ARX Playbook Coach',
    observation: 'Active playbook contains 12 verified rules: 5 "DO MORE", 4 "STOP DOING", and 3 "CALIBRATE".',
    understanding: 'Rule #3 ("Never enter momentum break after 2:30 PM EST") has completely eliminated a historical -28.4% drag.',
    recommendation: 'Graduate Rule #3 from active monitoring to permanent automated order routing constraint.',
    confidence: 96,
    justification: 'Rule has 98% user compliance over 45 days with zero recorded violations and +$18.4k capital preserved.',
    projectedImpact: '+1.4 pts Risk Efficiency',
    evidenceHash: 'e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6',
    sampleSize: 95,
    pValue: 0.0002,
    tags: ['Rule Graduation', 'Constraint Locking', 'Execution Automation'],
  },
  GOVERNANCE: {
    context: 'GOVERNANCE',
    roleName: 'ARX Governance Guardian',
    observation: 'All 6 pre-flight release gates and 12-rule invariant checks are fully satisfied for current portfolio allocations.',
    understanding: 'No single ticker exceeds 5% capital limit; portfolio beta remains locked at 1.05 (limit 1.20). SEC/FINRA ledger intact.',
    recommendation: 'Issue official Go verdict for Stage 4 execution. Maintain portfolio-level stop at -2.5% max daily drawdown.',
    confidence: 99,
    justification: 'Deterministic multi-party consensus verified with cryptographic SHA-256 signatures across all risk boundaries.',
    projectedImpact: '100% Invariant Compliance',
    evidenceHash: 'f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7',
    sampleSize: 250,
    pValue: 0.00001,
    tags: ['Release Gate', 'Capital Limit', 'Regulatory Compliance'],
  },
};

export const MOCK_INSIGHT_CARDS: StandardInsightData[] = [
  {
    id: 'ins-1',
    ticker: 'CPRX',
    headline: 'Institutional Accumulation Spike Detected',
    observation: 'Block orders detected across dark pools representing 34% of daily average volume within 45 minutes.',
    category: 'FLOW',
    confidence: 92,
    metricDelta: { label: 'Flow Delta', value: '+2.4σ', isPositive: true },
    timestamp: 'Today, 09:31 EST',
    source: 'Dark Pool & Institutional Tape Engine',
  },
  {
    id: 'ins-2',
    ticker: 'NVDA',
    headline: 'Macro Regime Shift to Technology Resilience',
    observation: 'Semiconductor sub-index beta decoupled from 10-year Treasury yield spikes (+0.14 vs historical -0.65).',
    category: 'REGIME',
    confidence: 89,
    metricDelta: { label: 'Beta Shift', value: '+0.79Δ', isPositive: true },
    timestamp: 'Today, 09:15 EST',
    source: 'Macro Regime Matrix',
  },
  {
    id: 'ins-3',
    ticker: 'AAPL',
    headline: 'Late-Day Momentum Exhaustion Risk',
    observation: 'Buying volume deceleration observed into session close; RSI divergence at +78 peak.',
    category: 'MOMENTUM',
    confidence: 86,
    metricDelta: { label: 'Volume Flow', value: '-1.8σ', isPositive: false },
    timestamp: 'Yesterday, 15:45 EST',
    source: 'Intraday Momentum Monitor',
  },
];

export const MOCK_RECOMMENDATION_CARDS: StandardRecommendationData[] = [
  {
    id: 'rec-1',
    ticker: 'CPRX',
    action: 'Enter Stage 2 Breakout Tranche',
    category: 'DO_MORE',
    rationale: 'Matches your highest-edge profile (72.4% win rate, +43.5% excess return). Execute standard allocation.',
    projectedImpact: '+3.4 pts',
    urgency: 'HIGH',
    confidence: 91,
    primaryActionLabel: 'Execute Order',
    secondaryActionLabel: 'Inspect Setup',
  },
  {
    id: 'rec-2',
    ticker: 'TSLA',
    action: 'Reject Breakout Entry After 2:30 PM',
    category: 'STOP_DOING',
    rationale: 'Violates Playbook Rule #3. Late momentum breakouts result in 35% win rate and -28.4% return drag for your profile.',
    projectedImpact: '+4.1 pts',
    urgency: 'HIGH',
    confidence: 94,
    primaryActionLabel: 'Enforce Rule',
    secondaryActionLabel: 'Dismiss',
  },
  {
    id: 'rec-3',
    ticker: 'AMD',
    action: 'Calibrate Trailing Stop to 2.2x ATR',
    category: 'CALIBRATE',
    rationale: 'Current 1.5x ATR stop is triggering premature noise exits. Widening to 2.2x preserves +3.1% additional capture.',
    projectedImpact: '+1.9 pts',
    urgency: 'MEDIUM',
    confidence: 88,
    primaryActionLabel: 'Update Stop Limit',
    secondaryActionLabel: 'Simulate',
  },
];

export const MOCK_LEARNING_CARDS: StandardLearningData[] = [
  {
    id: 'lrn-1',
    ticker: 'CPRX',
    title: 'Flow-Confirmed Breakouts Yield +14.2% Higher Alpha',
    takeaway: 'Waiting for institutional dark pool flow (>2.0σ) before entering breakouts reduces false breakouts by 41%.',
    causalFactor: 'Institutional Order Flow Aggregation',
    winRateImpact: '+14.2% Win Rate',
    errorElimination: '-41% False Breakouts',
    ruleRefinementProposal: 'Mandate minimum 1.8σ flow confirmation on all small-cap biotech trades.',
    statisticalStrength: 'VERY_HIGH',
  },
  {
    id: 'lrn-2',
    ticker: 'PORTFOLIO',
    title: 'Adherence to Stop Discipline Boosted Score by +6.2 Points',
    takeaway: 'Eliminating stop adjustments lower during market drawdowns preserved $42,500 in simulated risk capital.',
    causalFactor: 'Disciplined Execution & Zero Downward Stop Revisions',
    winRateImpact: '+8.7% Portfolio Sharpe',
    errorElimination: '-52% Maximum Drawdown Tail',
    ruleRefinementProposal: 'Lock stops into execution broker with one-way upward trailing ratchet.',
    statisticalStrength: 'VERY_HIGH',
  },
];

export const MOCK_EVIDENCE_CARDS: StandardEvidenceData[] = [
  {
    id: 'ev-1',
    claim: 'Institutional flow surge > 2.0σ increases 5-day breakout probability from 51% to 78.4%',
    sampleSize: 124,
    pValue: 0.0003,
    sharpeImpact: '+0.42 Sharpe',
    lookbackPeriod: '180 Trading Days',
    ledgerHash: 'b3f1a8c9e4d207b56a319f09e81b6a7d5c4e3f2a1b0d8e7c6b5a4f3e2d1c0b9a',
    verifiedAt: '2026-09-07 16:30 UTC',
  },
  {
    id: 'ev-2',
    claim: 'Late-day entries after 14:30 EST exhibit negative statistical expectancy (-0.38 Sharpe)',
    sampleSize: 86,
    pValue: 0.0018,
    sharpeImpact: '-0.38 Sharpe (Avoided)',
    lookbackPeriod: '180 Trading Days',
    ledgerHash: '7d5c4e3f2a1b0d8e7c6b5a4f3e2d1c0b9a8f7e6d5c4b3ab3f1a8c9e4d207b56a',
    verifiedAt: '2026-09-07 16:30 UTC',
  },
];
