/**
 * ARX Terminal Master Asset Catalog (Single Source of Truth)
 * 
 * Consolidates all static baseline asset profiles, authentic fundamental metrics,
 * execution price boundaries, and risk parameters into a unified, strongly-typed repository.
 * Eliminates dual-maintenance drift across Screener, Terminal, Compare, Strategy, and Radar hubs.
 */

export interface MasterAssetEntry {
  symbol: string;
  name: string;
  price: number;
  changePct: number;
  type: "Stock" | "ETF" | "Crypto";
  sector: string;
  category: string;
  roic: number;
  grossMargin: number;
  fwdPe: number;
  peg: number;
  fcfYield: number;
  piotroski: number;
  atr14: number;
  rvol: number;
  shortFloat: number;
  beta: number;
  marketCap: string;
  growthScore: number;
  qualityScore: number;
  valuationScore: number;
  momentumScore: number;
  tailRiskScore: number;
  compositeFactorScore: number;
  verdict: string;
  moatSummary: string;
  upcomingCatalyst: string;
  thesis: string;
}

export const MASTER_ASSET_CATALOG: Record<string, MasterAssetEntry> = {
  // Mega-Cap Tech & AI Infrastructure
  NVDA: {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 128.50,
    changePct: 3.14,
    type: "Stock",
    sector: "Technology",
    category: "AI Datacenter Monopoly",
    roic: 48.0,
    grossMargin: 75.2,
    fwdPe: 32.4,
    peg: 0.92,
    fcfYield: 3.1,
    piotroski: 8,
    atr14: 4.85,
    rvol: 2.8,
    shortFloat: 2.2,
    beta: 1.74,
    marketCap: "$3,150B",
    growthScore: 96,
    qualityScore: 95,
    valuationScore: 68,
    momentumScore: 94,
    tailRiskScore: 76,
    compositeFactorScore: 91,
    verdict: "Exceptional Growth Leader",
    moatSummary: "CUDA software ecosystem and proprietary NVLink interconnect architecture create high switching costs for hyperscaler AI training clusters.",
    upcomingCatalyst: "Blackwell Ultra GPU volume ramp, sovereign AI datacenter procurement, and Rubin architecture tape-out.",
    thesis: "3-Stage contraction handle resting above 20 EMA with Blackwell datacenter ramp."
  },
  AAPL: {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 319.64,
    changePct: 2.62,
    type: "Stock",
    sector: "Technology",
    category: "Consumer Hardware & Services Ecosystem",
    roic: 45.0,
    grossMargin: 46.0,
    fwdPe: 28.5,
    peg: 1.30,
    fcfYield: 4.2,
    piotroski: 8,
    atr14: 2.40,
    rvol: 1.2,
    shortFloat: 1.4,
    beta: 0.95,
    marketCap: "$3,450B",
    growthScore: 84,
    qualityScore: 90,
    valuationScore: 72,
    momentumScore: 78,
    tailRiskScore: 82,
    compositeFactorScore: 82,
    verdict: "Strong Buy / Core Hold",
    moatSummary: "2.2B+ active device ecosystem with privacy-first Apple Intelligence and high-margin services annuity.",
    upcomingCatalyst: "Apple Intelligence Global Rollout & WWDC Next-Gen Developer Silicon Showcase.",
    thesis: "High free-cash-flow yield compounder with resilient consumer ecosystem."
  },
  MSFT: {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 418.20,
    changePct: 0.85,
    type: "Stock",
    sector: "Technology",
    category: "Enterprise Cloud & Enterprise AI",
    roic: 36.0,
    grossMargin: 69.5,
    fwdPe: 31.0,
    peg: 1.22,
    fcfYield: 3.3,
    piotroski: 9,
    atr14: 5.20,
    rvol: 1.4,
    shortFloat: 1.2,
    beta: 1.05,
    marketCap: "$3,120B",
    growthScore: 86,
    qualityScore: 96,
    valuationScore: 70,
    momentumScore: 80,
    tailRiskScore: 88,
    compositeFactorScore: 87,
    verdict: "Fortress Balance Sheet",
    moatSummary: "Enterprise software foundation (Office 365/Copilot) coupled with Azure hyper-scale cloud AI hosting.",
    upcomingCatalyst: "Enterprise Copilot Seat Monetization & Sovereign Cloud Defense Security Approvals.",
    thesis: "Fortress balance sheet with secular cloud and enterprise AI monetization."
  },
  GOOGL: {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    price: 164.80,
    changePct: 1.40,
    type: "Stock",
    sector: "Communication Services",
    category: "Search & Cloud Infrastructure",
    roic: 32.0,
    grossMargin: 57.5,
    fwdPe: 21.0,
    peg: 1.05,
    fcfYield: 4.8,
    piotroski: 8,
    atr14: 3.10,
    rvol: 1.4,
    shortFloat: 1.1,
    beta: 1.08,
    marketCap: "$2,050B",
    growthScore: 85,
    qualityScore: 93,
    valuationScore: 78,
    momentumScore: 82,
    tailRiskScore: 86,
    compositeFactorScore: 86,
    verdict: "Deep Value & AI Moat",
    moatSummary: "Global search market dominance, YouTube digital media reach, and Google Cloud TPU infrastructure.",
    upcomingCatalyst: "Gemini 2.5 multimodal enterprise integration and autonomous Waymo expansion.",
    thesis: "Deep value valuation with massive free cash flow generation."
  },
  TSLA: {
    symbol: "TSLA",
    name: "Tesla Inc.",
    price: 218.40,
    changePct: 2.15,
    type: "Stock",
    sector: "Consumer Cyclical",
    category: "Autonomous Robotics & EV Fleet",
    roic: 16.0,
    grossMargin: 18.2,
    fwdPe: 65.0,
    peg: 1.60,
    fcfYield: 1.5,
    piotroski: 6,
    atr14: 8.40,
    rvol: 3.1,
    shortFloat: 6.8,
    beta: 2.15,
    marketCap: "$695B",
    growthScore: 80,
    qualityScore: 82,
    valuationScore: 55,
    momentumScore: 88,
    tailRiskScore: 68,
    compositeFactorScore: 77,
    verdict: "High Beta Autonomy Speculation",
    moatSummary: "Leading autonomous vehicle compute network (FSD v13) and Megapack grid storage utility growth.",
    upcomingCatalyst: "Full Self-Driving (FSD) Unsupervised Regulatory Pilot Expansion & Cybercab Production Ramp.",
    thesis: "High-beta growth speculation on autonomous vehicle and energy storage scale."
  },
  PLTR: {
    symbol: "PLTR",
    name: "Palantir Technologies",
    price: 31.20,
    changePct: 4.12,
    type: "Stock",
    sector: "Technology",
    category: "Defense & Enterprise AI Operating System",
    roic: 23.0,
    grossMargin: 81.0,
    fwdPe: 78.0,
    peg: 1.25,
    fcfYield: 2.8,
    piotroski: 8,
    atr14: 1.65,
    rvol: 3.8,
    shortFloat: 7.2,
    beta: 1.85,
    marketCap: "$70B",
    growthScore: 94,
    qualityScore: 90,
    valuationScore: 62,
    momentumScore: 95,
    tailRiskScore: 74,
    compositeFactorScore: 87,
    verdict: "Commercial AI Breakout",
    moatSummary: "Mission-critical defense ontology (Gotham) and enterprise Artificial Intelligence Platform (AIP).",
    upcomingCatalyst: "US Army TITAN System Full-Rate Production Decision & Intelligence Community SaaS Contract Award.",
    thesis: "High-density institutional accumulation handle following TITAN contract award."
  },
  NVO: {
    symbol: "NVO",
    name: "Novo Nordisk A/S",
    price: 45.31,
    changePct: -3.18,
    type: "Stock",
    sector: "Healthcare",
    category: "GLP-1 Incretin & Metabolic Duopoly",
    roic: 54.0,
    grossMargin: 84.5,
    fwdPe: 29.2,
    peg: 0.88,
    fcfYield: 3.8,
    piotroski: 9,
    atr14: 2.10,
    rvol: 2.3,
    shortFloat: 1.5,
    beta: 0.72,
    marketCap: "$610B",
    growthScore: 89,
    qualityScore: 94,
    valuationScore: 74,
    momentumScore: 86,
    tailRiskScore: 85,
    compositeFactorScore: 88,
    verdict: "High Quality Compounder",
    moatSummary: "Global GLP-1 weight-loss duopoly with Semaglutide/Wegovy franchise and oral formulation pipeline.",
    upcomingCatalyst: "Medicare Part D Expanded GLP-1 Reimbursement Senate Floor Vote & Catalent Manufacturing Expansion.",
    thesis: "Orphan franchise with 84%+ gross margins and pristine 9/9 Piotroski balance sheet."
  },
  LLY: {
    symbol: "LLY",
    name: "Eli Lilly and Company",
    price: 924.50,
    changePct: 2.10,
    type: "Stock",
    sector: "Healthcare",
    category: "Metabolic, Oncology & Immunology Leader",
    roic: 38.2,
    grossMargin: 80.2,
    fwdPe: 34.0,
    peg: 1.28,
    fcfYield: 2.4,
    piotroski: 8,
    atr14: 14.50,
    rvol: 2.1,
    shortFloat: 1.8,
    beta: 0.78,
    marketCap: "$875B",
    growthScore: 92,
    qualityScore: 91,
    valuationScore: 65,
    momentumScore: 90,
    tailRiskScore: 81,
    compositeFactorScore: 86,
    verdict: "Secular Pharma Leader",
    moatSummary: "Secular obesity and diabetes powerhouse (Mounjaro/Zepbound) and Alzheimer's monoclonal antibody.",
    upcomingCatalyst: "Phase 3 Triple-Agonist Retatrutide readout and international reimbursement authorizations.",
    thesis: "Secular healthcare compounder with strong pricing power and pipeline moats."
  },
  LNTH: {
    symbol: "LNTH",
    name: "Lantheus Holdings",
    price: 100.78,
    changePct: -4.09,
    type: "Stock",
    sector: "Healthcare",
    category: "Radiopharmaceutical & PET Oncology Monopolist",
    roic: 38.5,
    grossMargin: 68.5,
    fwdPe: 18.2,
    peg: 0.82,
    fcfYield: 6.2,
    piotroski: 9,
    atr14: 2.80,
    rvol: 2.4,
    shortFloat: 4.8,
    beta: 1.10,
    marketCap: "$6.9B",
    growthScore: 88,
    qualityScore: 92,
    valuationScore: 80,
    momentumScore: 79,
    tailRiskScore: 84,
    compositeFactorScore: 85,
    verdict: "Radiopharmaceutical Monopoly",
    moatSummary: "Diagnostic imaging market leader with patent exclusivity on radiopharmaceuticals.",
    upcomingCatalyst: "CMS diagnostic reimbursement policy finalization.",
    thesis: "Radiopharmaceutical diagnostic monopoly trading at deep valuation discount."
  },
  CPRX: {
    symbol: "CPRX",
    name: "Catalyst Pharmaceuticals",
    price: 31.49,
    changePct: 0.00,
    type: "Stock",
    sector: "Healthcare",
    category: "Rare Neurological Commercial Monopoly",
    roic: 42.8,
    grossMargin: 82.5,
    fwdPe: 16.4,
    peg: 0.74,
    fcfYield: 5.8,
    piotroski: 9,
    atr14: 0.85,
    rvol: 2.8,
    shortFloat: 5.2,
    beta: 0.90,
    marketCap: "$2.8B",
    growthScore: 89,
    qualityScore: 95,
    valuationScore: 84,
    momentumScore: 82,
    tailRiskScore: 88,
    compositeFactorScore: 88,
    verdict: "Pristine Balance Sheet Compounder",
    moatSummary: "Commercial monopoly on rare neuromuscular treatments with 88%+ gross margins.",
    upcomingCatalyst: "Agamree Duchenne muscular dystrophy international commercial rollout.",
    thesis: "Orphan disease franchise with 88%+ gross margins and pristine 9/9 Piotroski balance sheet."
  },
  MEDP: {
    symbol: "MEDP",
    name: "Medpace Holdings",
    price: 342.10,
    changePct: 1.45,
    type: "Stock",
    sector: "Healthcare",
    category: "Clinical Research Organization",
    roic: 36.8,
    grossMargin: 71.0,
    fwdPe: 19.8,
    peg: 0.92,
    fcfYield: 5.1,
    piotroski: 9,
    atr14: 8.50,
    rvol: 1.8,
    shortFloat: 3.5,
    beta: 1.15,
    marketCap: "$10.5B",
    growthScore: 87,
    qualityScore: 94,
    valuationScore: 78,
    momentumScore: 83,
    tailRiskScore: 86,
    compositeFactorScore: 86,
    verdict: "Zero Debt CRO Leader",
    moatSummary: "Specialized clinical research outsourcing with zero long-term debt and high organic retention.",
    upcomingCatalyst: "Biotech funding cycle recovery and Phase 3 trial starts.",
    thesis: "Full-service clinical CRO compounder with zero long-term debt."
  },
  TMDX: {
    symbol: "TMDX",
    name: "TransMedics Group",
    price: 92.60,
    changePct: 3.15,
    type: "Stock",
    sector: "Healthcare",
    category: "Organ Perfusion Technology",
    roic: 27.8,
    grossMargin: 78.4,
    fwdPe: 38.0,
    peg: 1.15,
    fcfYield: 2.1,
    piotroski: 8,
    atr14: 3.40,
    rvol: 3.2,
    shortFloat: 8.4,
    beta: 1.60,
    marketCap: "$3.1B",
    growthScore: 91,
    qualityScore: 89,
    valuationScore: 64,
    momentumScore: 88,
    tailRiskScore: 74,
    compositeFactorScore: 82,
    verdict: "Category Disruptor",
    moatSummary: "Organ Care System (OCS) warm-perfusion donor organ transport monopoly.",
    upcomingCatalyst: "National aviation fleet expansion and donor organ utilization report.",
    thesis: "Organ Care System (OCS) warm-perfusion donor organ transport monopoly."
  },
  VRT: {
    symbol: "VRT",
    name: "Vertiv Holdings",
    price: 114.20,
    changePct: 2.85,
    type: "Stock",
    sector: "Industrials",
    category: "AI Datacenter Power & Liquid Cooling",
    roic: 28.6,
    grossMargin: 54.2,
    fwdPe: 28.0,
    peg: 0.92,
    fcfYield: 3.8,
    piotroski: 7,
    atr14: 3.80,
    rvol: 3.5,
    shortFloat: 4.6,
    beta: 1.70,
    marketCap: "$43B",
    growthScore: 92,
    qualityScore: 88,
    valuationScore: 70,
    momentumScore: 92,
    tailRiskScore: 78,
    compositeFactorScore: 85,
    verdict: "Datacenter Infrastructure Leader",
    moatSummary: "High-density thermal management and liquid cooling systems for next-gen GPU server racks.",
    upcomingCatalyst: "Tier-1 cloud provider liquid cooling multi-gigawatt procurement deals.",
    thesis: "Liquid cooling AI datacenter infrastructure breakout expanding toward Target 1."
  },
  DUOL: {
    symbol: "DUOL",
    name: "Duolingo Inc.",
    price: 312.80,
    changePct: 3.20,
    type: "Stock",
    sector: "Technology",
    category: "EdTech AI & Learning Platform",
    roic: 29.4,
    grossMargin: 73.5,
    fwdPe: 44.0,
    peg: 1.10,
    fcfYield: 3.9,
    piotroski: 8,
    atr14: 9.20,
    rvol: 3.6,
    shortFloat: 8.5,
    beta: 1.45,
    marketCap: "$13.8B",
    growthScore: 93,
    qualityScore: 91,
    valuationScore: 66,
    momentumScore: 91,
    tailRiskScore: 79,
    compositeFactorScore: 85,
    verdict: "Generative AI Consumer Leader",
    moatSummary: "Gamified generative AI language & math learning with 73% gross margins and high daily active user retention.",
    upcomingCatalyst: "Max subscription tier rollout and math/music curriculum expansion.",
    thesis: "Gamified generative AI language & math learning with 73% gross margins."
  },
  SMCI: {
    symbol: "SMCI",
    name: "Super Micro Computer",
    price: 48.20,
    changePct: 5.40,
    type: "Stock",
    sector: "Technology",
    category: "Accelerated Server Architecture",
    roic: 22.4,
    grossMargin: 52.0,
    fwdPe: 16.5,
    peg: 0.72,
    fcfYield: 2.5,
    piotroski: 7,
    atr14: 3.90,
    rvol: 4.2,
    shortFloat: 14.8,
    beta: 2.20,
    marketCap: "$28B",
    growthScore: 84,
    qualityScore: 78,
    valuationScore: 82,
    momentumScore: 88,
    tailRiskScore: 68,
    compositeFactorScore: 80,
    verdict: "High-Beta Server Turnaround",
    moatSummary: "Modular server building-block solutions optimized for NVIDIA AI superclusters.",
    upcomingCatalyst: "Special committee independent audit review filing & FY25 revenue updates.",
    thesis: "Deep value server turnaround play undergoing independent review."
  },
  ULTA: {
    symbol: "ULTA",
    name: "Ulta Beauty Inc.",
    price: 368.40,
    changePct: 0.85,
    type: "Stock",
    sector: "Consumer Cyclical",
    category: "Specialty Retail & Beauty (Stage 4 Turnaround)",
    roic: 35.5,
    grossMargin: 52.8,
    fwdPe: 13.5,
    peg: 0.79,
    fcfYield: 7.2,
    piotroski: 7,
    atr14: 7.40,
    rvol: 2.2,
    shortFloat: 4.5,
    beta: 1.15,
    marketCap: "$17.4B",
    growthScore: 54,
    qualityScore: 86,
    valuationScore: 88,
    momentumScore: 48,
    tailRiskScore: 72,
    compositeFactorScore: 69,
    verdict: "Deep Value / Turnaround Watch",
    moatSummary: "Dominant loyalty program (44M+ active members) and high ROIC, currently navigating post-COVID prestige comp deceleration.",
    upcomingCatalyst: "Holiday seasonal comp inflection and Berkshire Hathaway value accumulation follow-through.",
    thesis: "High-ROIC specialty retailer trading at compressed multiple (13.5x P/E) under Stage 4 turnaround watch."
  },
  LULU: {
    symbol: "LULU",
    name: "Lululemon Athletica",
    price: 264.50,
    changePct: -0.45,
    type: "Stock",
    sector: "Consumer Cyclical",
    category: "Athletic Apparel & Technical Gear (Stage 4 Turnaround)",
    roic: 31.0,
    grossMargin: 58.5,
    fwdPe: 18.2,
    peg: 0.88,
    fcfYield: 5.4,
    piotroski: 7,
    atr14: 6.80,
    rvol: 2.5,
    shortFloat: 6.2,
    beta: 1.25,
    marketCap: "$32.8B",
    growthScore: 58,
    qualityScore: 88,
    valuationScore: 82,
    momentumScore: 52,
    tailRiskScore: 74,
    compositeFactorScore: 71,
    verdict: "Deep Value / Mean-Reversion Watch",
    moatSummary: "Premium athletic apparel brand with pristine balance sheet, facing North American consumer normalization.",
    upcomingCatalyst: "New product line execution, seasonal outerwear launch, and China store growth.",
    thesis: "High-margin athletic lifestyle leader navigating North American comp deceleration."
  },
  CELH: {
    symbol: "CELH",
    name: "Celsius Holdings",
    price: 36.80,
    changePct: 3.85,
    type: "Stock",
    sector: "Consumer Defensive",
    category: "Functional Energy Beverages",
    roic: 21.0,
    grossMargin: 52.0,
    fwdPe: 26.0,
    peg: 0.92,
    fcfYield: 4.2,
    piotroski: 7,
    atr14: 1.80,
    rvol: 3.3,
    shortFloat: 9.2,
    beta: 1.65,
    marketCap: "$8.6B",
    growthScore: 84,
    qualityScore: 83,
    valuationScore: 75,
    momentumScore: 82,
    tailRiskScore: 76,
    compositeFactorScore: 80,
    verdict: "Beverage Growth Compounder",
    moatSummary: "High market-share fitness beverage with PepsiCo global distribution partnership.",
    upcomingCatalyst: "International territory launches and convenience store shelf-space expansion.",
    thesis: "9.2% Short Float with PepsiCo international distribution expansion."
  },
  // Core Benchmarks & ETFs
  SPY: {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    price: 765.91,
    changePct: 0.65,
    type: "ETF",
    sector: "Index",
    category: "US Large-Cap Core Equity Benchmark",
    roic: 18.5,
    grossMargin: 0,
    fwdPe: 24.5,
    peg: 1.35,
    fcfYield: 3.5,
    piotroski: 8,
    atr14: 4.50,
    rvol: 1.0,
    shortFloat: 0.5,
    beta: 1.00,
    marketCap: "$560B (AUM)",
    growthScore: 75,
    qualityScore: 88,
    valuationScore: 75,
    momentumScore: 80,
    tailRiskScore: 90,
    compositeFactorScore: 82,
    verdict: "Core Index Benchmark",
    moatSummary: "Market-cap weighted index representing the 500 leading publicly traded US corporations.",
    upcomingCatalyst: "Federal Reserve FOMC rate decisions and quarterly corporate earnings aggregate.",
    thesis: "Foundational equity market exposure."
  },
  QQQ: {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    price: 710.72,
    changePct: 1.10,
    type: "ETF",
    sector: "Index",
    category: "Nasdaq-100 Large-Cap Growth Benchmark",
    roic: 26.0,
    grossMargin: 0,
    fwdPe: 28.0,
    peg: 1.25,
    fcfYield: 2.9,
    piotroski: 8,
    atr14: 6.80,
    rvol: 1.3,
    shortFloat: 0.8,
    beta: 1.18,
    marketCap: "$285B (AUM)",
    growthScore: 85,
    qualityScore: 90,
    valuationScore: 72,
    momentumScore: 86,
    tailRiskScore: 84,
    compositeFactorScore: 85,
    verdict: "Nasdaq-100 Growth Engine",
    moatSummary: "Concentrated basket of the top 100 non-financial innovation leaders.",
    upcomingCatalyst: "Mega-cap tech capex announcements and macroeconomic liquidity cycle.",
    thesis: "Large-cap secular technology and innovation growth exposure."
  },
  SMH: {
    symbol: "SMH",
    name: "VanEck Semiconductor ETF",
    price: 288.40,
    changePct: 2.45,
    type: "ETF",
    sector: "Semiconductors",
    category: "Global Semiconductor Industry",
    roic: 32.0,
    grossMargin: 0,
    fwdPe: 26.5,
    peg: 1.10,
    fcfYield: 3.2,
    piotroski: 8,
    atr14: 7.20,
    rvol: 2.2,
    shortFloat: 1.2,
    beta: 1.55,
    marketCap: "$22B (AUM)",
    growthScore: 92,
    qualityScore: 90,
    valuationScore: 68,
    momentumScore: 92,
    tailRiskScore: 78,
    compositeFactorScore: 88,
    verdict: "Semiconductor Supercycle",
    moatSummary: "High-exposure pure-play ETF covering leading global chip designers, foundries, and lithography toolmakers.",
    upcomingCatalyst: "Next-gen compute node migrations and hyperscaler silicon spend.",
    thesis: "Semiconductor hardware supercycle exposure."
  },
  // High-Moat Semiconductors & Specialized Equipment
  POWI: {
    symbol: "POWI",
    name: "Power Integrations Inc.",
    price: 68.50,
    changePct: 1.45,
    type: "Stock",
    sector: "Semiconductors",
    category: "GaN & High-Voltage Power Conversion",
    roic: 24.5,
    grossMargin: 54.8,
    fwdPe: 24.2,
    peg: 0.92,
    fcfYield: 4.8,
    piotroski: 8,
    atr14: 2.40,
    rvol: 2.1,
    shortFloat: 3.4,
    beta: 1.35,
    marketCap: "$4.1B",
    growthScore: 78,
    qualityScore: 88,
    valuationScore: 82,
    momentumScore: 76,
    tailRiskScore: 85,
    compositeFactorScore: 82,
    verdict: "Peter Lynch GARP Compounder",
    moatSummary: "Niche monopoly in energy-efficient Gallium Nitride (GaN) and high-voltage power conversion chips.",
    upcomingCatalyst: "Server power supply efficiency mandates and GaN adoption in high-power appliances.",
    thesis: "Niche power semiconductor leader with strong balance sheet and zero long-term debt."
  },
  ACLS: {
    symbol: "ACLS",
    name: "Axcelis Technologies",
    price: 84.20,
    changePct: 2.10,
    type: "Stock",
    sector: "Semiconductors",
    category: "SiC Ion Implantation Capital Equipment",
    roic: 32.8,
    grossMargin: 46.2,
    fwdPe: 16.5,
    peg: 0.74,
    fcfYield: 6.2,
    piotroski: 8,
    atr14: 3.80,
    rvol: 2.4,
    shortFloat: 4.8,
    beta: 1.62,
    marketCap: "$3.2B",
    growthScore: 82,
    qualityScore: 91,
    valuationScore: 89,
    momentumScore: 80,
    tailRiskScore: 78,
    compositeFactorScore: 85,
    verdict: "Peter Lynch GARP Compounder",
    moatSummary: "Dominant supplier of high-energy Purion ion implantation systems vital for silicon carbide (SiC) power chips.",
    upcomingCatalyst: "Purion platform adoption in EV inverters and industrial renewable energy grid chips.",
    thesis: "High return on capital with low PEG (0.74) and pristine net cash position."
  },
  ELF: {
    symbol: "ELF",
    name: "e.l.f. Beauty Inc.",
    price: 118.40,
    changePct: 2.85,
    type: "Stock",
    sector: "Consumer Cyclical",
    category: "Digitally-Native Beauty & Cosmetics",
    roic: 28.4,
    grossMargin: 71.2,
    fwdPe: 28.5,
    peg: 0.84,
    fcfYield: 4.5,
    piotroski: 8,
    atr14: 5.40,
    rvol: 2.6,
    shortFloat: 6.8,
    beta: 1.45,
    marketCap: "$9.2B",
    growthScore: 89,
    qualityScore: 92,
    valuationScore: 80,
    momentumScore: 86,
    tailRiskScore: 80,
    compositeFactorScore: 86,
    verdict: "Peter Lynch GARP Compounder",
    moatSummary: "Disruptive beauty brand taking rapid global market share with digitally-native marketing and negative working capital.",
    upcomingCatalyst: "International retail expansion (UK/Europe) and premium skincare segment acquisitions.",
    thesis: "71.2% gross margins with rapid top-line market share gains."
  },
  ISRG: {
    symbol: "ISRG",
    name: "Intuitive Surgical",
    price: 446.50,
    changePct: 1.65,
    type: "Stock",
    sector: "Healthcare",
    category: "Robotic-Assisted Surgery Monopoly",
    roic: 22.5,
    grossMargin: 67.5,
    fwdPe: 48.0,
    peg: 1.45,
    fcfYield: 2.8,
    piotroski: 9,
    atr14: 8.60,
    rvol: 1.5,
    shortFloat: 1.1,
    beta: 1.15,
    marketCap: "$158.2B",
    growthScore: 86,
    qualityScore: 96,
    valuationScore: 62,
    momentumScore: 84,
    tailRiskScore: 92,
    compositeFactorScore: 85,
    verdict: "Pristine MedTech Monopoly",
    moatSummary: "da Vinci surgical system installed base (>9,000 systems) with high-margin recurring instrument and accessory revenue.",
    upcomingCatalyst: "da Vinci 5 commercial placement ramp and expanded surgical indication approvals.",
    thesis: "Pristine balance sheet with over $8B net cash and 9/9 Piotroski score."
  },
  VRTX: {
    symbol: "VRTX",
    name: "Vertex Pharmaceuticals",
    price: 482.10,
    changePct: 1.20,
    type: "Stock",
    sector: "Healthcare",
    category: "Cystic Fibrosis Monopoly & Gene Editing",
    roic: 28.8,
    grossMargin: 86.4,
    fwdPe: 26.5,
    peg: 0.98,
    fcfYield: 4.8,
    piotroski: 8,
    atr14: 9.20,
    rvol: 1.6,
    shortFloat: 1.4,
    beta: 0.72,
    marketCap: "$124.5B",
    growthScore: 88,
    qualityScore: 95,
    valuationScore: 78,
    momentumScore: 82,
    tailRiskScore: 94,
    compositeFactorScore: 88,
    verdict: "Elite Biopharma Compounder",
    moatSummary: "Global monopoly on CFTR modulators with commercial launch of Casgevy CRISPR gene therapy and non-opioid pain pipeline.",
    upcomingCatalyst: "Suzetrigine (VX-548) FDA approval decision for acute and neuropathic pain.",
    thesis: "86.4% gross margins, non-correlated low beta (0.72), and massive cash generation."
  },
  COIN: {
    symbol: "COIN",
    name: "Coinbase Global Inc.",
    price: 212.30,
    changePct: 4.85,
    type: "Stock",
    sector: "Financial Services",
    category: "Institutional Crypto Custody & Exchange",
    roic: 22.0,
    grossMargin: 85.2,
    fwdPe: 28.4,
    peg: 0.88,
    fcfYield: 5.6,
    piotroski: 8,
    atr14: 11.40,
    rvol: 3.1,
    shortFloat: 5.4,
    beta: 2.85,
    marketCap: "$52.4B",
    growthScore: 92,
    qualityScore: 86,
    valuationScore: 76,
    momentumScore: 88,
    tailRiskScore: 68,
    compositeFactorScore: 83,
    verdict: "Crypto Infrastructure Leader",
    moatSummary: "Primary institutional custodian for 8 of 11 US spot Bitcoin ETFs with expanding Base Layer-2 sequencer revenue.",
    upcomingCatalyst: "US crypto regulatory legislation (FIT21 / SEC litigation resolution) and institutional staking expansion.",
    thesis: "Dominant regulated digital asset infrastructure with high operating leverage."
  },
  MSTR: {
    symbol: "MSTR",
    name: "MicroStrategy Inc.",
    price: 134.20,
    changePct: 6.40,
    type: "Stock",
    sector: "Technology",
    category: "Corporate Bitcoin Treasury & AI BI",
    roic: 18.5,
    grossMargin: 74.5,
    fwdPe: 34.0,
    peg: 1.20,
    fcfYield: 2.4,
    piotroski: 7,
    atr14: 10.80,
    rvol: 3.6,
    shortFloat: 14.8,
    beta: 3.10,
    marketCap: "$28.6B",
    growthScore: 90,
    qualityScore: 78,
    valuationScore: 65,
    momentumScore: 94,
    tailRiskScore: 58,
    compositeFactorScore: 78,
    verdict: "High-Beta Bitcoin Proxy",
    moatSummary: "Largest corporate holder of Bitcoin (>226,000 BTC) using low-cost convertible debt to accumulate spot reserves.",
    upcomingCatalyst: "S&P 500 index inclusion eligibility and Bitcoin halving cycle liquidity expansion.",
    thesis: "14.8% Short Float with high institutional accumulation and convex upside leverage."
  },
  CRWD: {
    symbol: "CRWD",
    name: "CrowdStrike Holdings",
    price: 272.50,
    changePct: 2.65,
    type: "Stock",
    sector: "Technology",
    category: "Cloud Cybersecurity & Falcon Platform",
    roic: 21.5,
    grossMargin: 75.8,
    fwdPe: 44.0,
    peg: 1.25,
    fcfYield: 3.8,
    piotroski: 7,
    atr14: 9.80,
    rvol: 2.2,
    shortFloat: 2.4,
    beta: 1.48,
    marketCap: "$66.8B",
    growthScore: 89,
    qualityScore: 88,
    valuationScore: 68,
    momentumScore: 78,
    tailRiskScore: 75,
    compositeFactorScore: 80,
    verdict: "Secular Cybersecurity Leader",
    moatSummary: "Falcon single-agent platform architecture with high gross retention (>97%) and multi-module customer adoption.",
    upcomingCatalyst: "Next-gen SIEM customer wins and Falcon Flex customer commitment renewals.",
    thesis: "Mission-critical enterprise security platform recovering customer trust and expanding free cash flow."
  },
  ANET: {
    symbol: "ANET",
    name: "Arista Networks",
    price: 324.50,
    changePct: 2.15,
    type: "Stock",
    sector: "Technology",
    category: "Hyperscale AI Cloud Networking",
    roic: 38.2,
    grossMargin: 64.2,
    fwdPe: 34.5,
    peg: 1.15,
    fcfYield: 4.2,
    piotroski: 9,
    atr14: 8.40,
    rvol: 1.8,
    shortFloat: 1.8,
    beta: 1.32,
    marketCap: "$101.8B",
    growthScore: 90,
    qualityScore: 96,
    valuationScore: 72,
    momentumScore: 88,
    tailRiskScore: 86,
    compositeFactorScore: 87,
    verdict: "Elite Cloud Networking Compounder",
    moatSummary: "EOS network operating system monopoly powering Ethernet switches inside Microsoft and Meta AI clusters.",
    upcomingCatalyst: "Ethernet vs InfiniBand AI cluster adoption and 800G switch transition.",
    thesis: "38.2% ROIC with over $5B net cash, zero debt, and 9/9 Piotroski score."
  },
  ARM: {
    symbol: "ARM",
    name: "Arm Holdings plc",
    price: 134.80,
    changePct: 3.80,
    type: "Stock",
    sector: "Technology",
    category: "Compute Architecture IP & Licensing",
    roic: 26.5,
    grossMargin: 96.0,
    fwdPe: 52.0,
    peg: 1.40,
    fcfYield: 2.2,
    piotroski: 8,
    atr14: 7.20,
    rvol: 2.8,
    shortFloat: 4.2,
    beta: 2.15,
    marketCap: "$141.2B",
    growthScore: 94,
    qualityScore: 95,
    valuationScore: 58,
    momentumScore: 90,
    tailRiskScore: 72,
    compositeFactorScore: 82,
    verdict: "Secular IP Monopoly",
    moatSummary: "Universal architecture standard for 99% of global smartphones, rapidly expanding into Armv9 datacenter AI server chips.",
    upcomingCatalyst: "Hyperscaler custom silicon adoption (AWS Graviton, Google Axion, Microsoft Cobalt).",
    thesis: "96.0% software gross margins with royalty rate expansion under Armv9."
  },
  AMD: {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    price: 146.20,
    changePct: 2.90,
    type: "Stock",
    sector: "Technology",
    category: "Datacenter AI Accelerators & x86 CPUs",
    roic: 19.5,
    grossMargin: 53.5,
    fwdPe: 28.5,
    peg: 0.95,
    fcfYield: 3.5,
    piotroski: 8,
    atr14: 5.60,
    rvol: 2.4,
    shortFloat: 2.1,
    beta: 1.82,
    marketCap: "$236.8B",
    growthScore: 88,
    qualityScore: 87,
    valuationScore: 78,
    momentumScore: 84,
    tailRiskScore: 78,
    compositeFactorScore: 83,
    verdict: "High-Beta Compute Challenger",
    moatSummary: "Instinct MI300X AI accelerator platform and EPYC datacenter CPU market-share gains against Intel.",
    upcomingCatalyst: "MI350X next-gen AI GPU launch and enterprise ROCm software maturity.",
    thesis: "Dual growth engine in enterprise server CPUs and merchant AI accelerators."
  },
  DECK: {
    symbol: "DECK",
    name: "Deckers Outdoor Corp.",
    price: 86.33,
    changePct: 1.80,
    type: "Stock",
    sector: "Consumer Cyclical",
    category: "Performance Footwear (HOKA & UGG)",
    roic: 38.5,
    grossMargin: 56.2,
    fwdPe: 22.0,
    peg: 0.92,
    fcfYield: 5.2,
    piotroski: 9,
    atr14: 2.80,
    rvol: 1.9,
    shortFloat: 3.2,
    beta: 0.98,
    marketCap: "$22.4B",
    growthScore: 89,
    qualityScore: 96,
    valuationScore: 82,
    momentumScore: 86,
    tailRiskScore: 88,
    compositeFactorScore: 89,
    verdict: "Peter Lynch GARP Compounder",
    moatSummary: "High brand-heat running shoe monopoly (HOKA) paired with high-margin luxury sheepskin footwear (UGG).",
    upcomingCatalyst: "Global direct-to-consumer store openings and international wholesale expansion.",
    thesis: "38.5% ROIC, 9/9 Piotroski score, and pristine balance sheet with zero debt."
  },
  ON: {
    symbol: "ON",
    name: "ON Semiconductor Corp.",
    price: 72.40,
    changePct: 1.95,
    type: "Stock",
    sector: "Semiconductors",
    category: "Silicon Carbide & Automotive Power",
    roic: 25.4,
    grossMargin: 46.8,
    fwdPe: 16.8,
    peg: 0.85,
    fcfYield: 5.8,
    piotroski: 8,
    atr14: 2.90,
    rvol: 2.0,
    shortFloat: 4.1,
    beta: 1.68,
    marketCap: "$30.8B",
    growthScore: 80,
    qualityScore: 88,
    valuationScore: 86,
    momentumScore: 78,
    tailRiskScore: 78,
    compositeFactorScore: 83,
    verdict: "Deep Value / GARP Compounder",
    moatSummary: "Leading vertically integrated manufacturer of silicon carbide (SiC) power modules for automotive EV drivetrains.",
    upcomingCatalyst: "Automotive inventory bottoming and renewable energy inverter volume ramp.",
    thesis: "Low multiple (16.8x P/E) with strong free cash flow yield (5.8%)."
  },
  MPWR: {
    symbol: "MPWR",
    name: "Monolithic Power Systems",
    price: 812.30,
    changePct: 2.40,
    type: "Stock",
    sector: "Semiconductors",
    category: "High-Efficiency Datacenter Power ICs",
    roic: 34.0,
    grossMargin: 55.4,
    fwdPe: 38.0,
    peg: 1.18,
    fcfYield: 3.4,
    piotroski: 9,
    atr14: 22.50,
    rvol: 1.9,
    shortFloat: 2.6,
    beta: 1.42,
    marketCap: "$39.2B",
    growthScore: 91,
    qualityScore: 96,
    valuationScore: 70,
    momentumScore: 88,
    tailRiskScore: 85,
    compositeFactorScore: 87,
    verdict: "Elite Power Silicon Compounder",
    moatSummary: "Proprietary BCD semiconductor process technology delivering highest power-density ICs for NVIDIA AI clusters.",
    upcomingCatalyst: "AI rack-level power delivery content expansion with next-gen hyperscale server deployments.",
    thesis: "34.0% ROIC, 9/9 Piotroski score, and multi-year secular power density tailwinds."
  },
  KLAC: {
    symbol: "KLAC",
    name: "KLA Corporation",
    price: 734.50,
    changePct: 2.10,
    type: "Stock",
    sector: "Semiconductors",
    category: "Process Control & Yield Inspection",
    roic: 38.5,
    grossMargin: 61.5,
    fwdPe: 24.5,
    peg: 1.02,
    fcfYield: 4.8,
    piotroski: 8,
    atr14: 18.20,
    rvol: 1.8,
    shortFloat: 1.5,
    beta: 1.40,
    marketCap: "$98.5B",
    growthScore: 88,
    qualityScore: 96,
    valuationScore: 78,
    momentumScore: 86,
    tailRiskScore: 84,
    compositeFactorScore: 87,
    verdict: "Semi Equipment Monopoly",
    moatSummary: "Over 55% global market share in semiconductor optical inspection and metrology tools essential for advanced nodes.",
    upcomingCatalyst: "Gate-All-Around (GAA) and High-NA EUV lithography inspection tool demand.",
    thesis: "Exceptional pricing power, 38.5% ROIC, and mission-critical foundry yield monopoly."
  },
  LRCX: {
    symbol: "LRCX",
    name: "Lam Research Corporation",
    price: 792.10,
    changePct: 2.30,
    type: "Stock",
    sector: "Semiconductors",
    category: "Atomic-Scale Etch & Deposition Systems",
    roic: 36.2,
    grossMargin: 48.2,
    fwdPe: 22.8,
    peg: 0.96,
    fcfYield: 5.1,
    piotroski: 8,
    atr14: 21.00,
    rvol: 1.9,
    shortFloat: 1.4,
    beta: 1.50,
    marketCap: "$103.2B",
    growthScore: 87,
    qualityScore: 94,
    valuationScore: 82,
    momentumScore: 85,
    tailRiskScore: 82,
    compositeFactorScore: 87,
    verdict: "Peter Lynch GARP Compounder",
    moatSummary: "Dominant etch toolmaker required for vertical 3D NAND flash stacking and High-Bandwidth Memory (HBM) packaging.",
    upcomingCatalyst: "HBM4 memory packaging expansion and advanced packaging deposition tool demand.",
    thesis: "36.2% ROIC, 0.96 PEG, and strong free cash flow yield (5.1%)."
  },
  // Digital Assets / Cryptocurrencies
  "BTC-USD": {
    symbol: "BTC-USD",
    name: "Bitcoin",
    price: 78213.00,
    changePct: 2.80,
    type: "Crypto",
    sector: "Digital Assets",
    category: "Decentralized Digital Commodity",
    roic: 0,
    grossMargin: 0,
    fwdPe: 0,
    peg: 0,
    fcfYield: 0,
    piotroski: 8,
    atr14: 2450.00,
    rvol: 2.5,
    shortFloat: 0,
    beta: 2.25,
    marketCap: "$1,540B",
    growthScore: 92,
    qualityScore: 95,
    valuationScore: 70,
    momentumScore: 88,
    tailRiskScore: 70,
    compositeFactorScore: 84,
    verdict: "Digital Monetary Gold",
    moatSummary: "Immutable proof-of-work monetary network with 21M hard cap and global institutional Spot ETF adoption.",
    upcomingCatalyst: "US Strategic Bitcoin Reserve legislation and institutional sovereign wealth allocation.",
    thesis: "Foundational digital store of value with fixed programmatic supply schedule."
  },
  "ETH-USD": {
    symbol: "ETH-USD",
    name: "Ethereum",
    price: 2438.00,
    changePct: 1.65,
    type: "Crypto",
    sector: "Digital Assets",
    category: "Decentralized Smart Contract Platform",
    roic: 0,
    grossMargin: 0,
    fwdPe: 0,
    peg: 0,
    fcfYield: 0,
    piotroski: 8,
    atr14: 95.00,
    rvol: 2.1,
    shortFloat: 0,
    beta: 2.45,
    marketCap: "$294B",
    growthScore: 88,
    qualityScore: 92,
    valuationScore: 74,
    momentumScore: 82,
    tailRiskScore: 72,
    compositeFactorScore: 82,
    verdict: "Smart Contract Settlement Layer",
    moatSummary: "Dominant Layer-1 smart contract ecosystem settling >$3T in annual stablecoin and DeFi transactions.",
    upcomingCatalyst: "Pectra network upgrade and Layer-2 blobspace scaling adoption.",
    thesis: "Primary global settlement layer for decentralized finance and tokenized real-world assets."
  },
  "SOL-USD": {
    symbol: "SOL-USD",
    name: "Solana",
    price: 96.73,
    changePct: 0.24,
    type: "Crypto",
    sector: "Digital Assets",
    category: "High-Throughput PoS Execution Layer",
    roic: 0,
    grossMargin: 0,
    fwdPe: 0,
    peg: 0,
    fcfYield: 0,
    piotroski: 8,
    atr14: 6.80,
    rvol: 2.8,
    shortFloat: 0,
    beta: 2.80,
    marketCap: "$45.2B",
    growthScore: 94,
    qualityScore: 86,
    valuationScore: 72,
    momentumScore: 86,
    tailRiskScore: 65,
    compositeFactorScore: 81,
    verdict: "High-Speed Execution Layer",
    moatSummary: "Sub-second finality monolithic blockchain processing over 2,500 real transactions per second.",
    upcomingCatalyst: "Firedancer validator client mainnet rollout and institutional Spot ETF applications.",
    thesis: "Dominant high-velocity retail trading, payments, and consumer crypto execution network."
  }
};

/**
 * Accessor Helpers
 */
export function getMasterAsset(symbol: string): MasterAssetEntry | undefined {
  if (!symbol) return undefined;
  const clean = symbol.toUpperCase().replace("-USD", "").trim();
  return MASTER_ASSET_CATALOG[clean];
}

export function getMasterPrice(symbol: string, fallback: number = 100.0): number {
  const asset = getMasterAsset(symbol);
  return asset ? asset.price : fallback;
}

export function getAllMasterTickers(): string[] {
  return Object.keys(MASTER_ASSET_CATALOG);
}
